// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Messages.V1_0_1;

/// <summary>Generated custom LLRP message 'MOTO_TAG_EVENT_NOTIFY'.</summary>
/// <param name="MessageId">The common LLRP message identifier.</param>
public sealed record MOTO_TAG_EVENT_NOTIFY(
    uint MessageId
) : global::LlrpNet.Protocol.Messages.ILlrpMessage
{
    public const ushort TypeNumber = 1023;
    public const ushort MessageType = TypeNumber;
    public const uint VendorIdentifier = 161U;
    public const byte Subtype = 5;
}
