// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Enumerations.V1_1;

/// <summary>Generated LLRP enumeration 'ROSpecStopTriggerType'.</summary>
public enum ROSpecStopTriggerType : long
{
    Null = 0L,
    Duration = 1L,
    GPI_With_Timeout = 2L,
}
