// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Enumerations.V1_1;

/// <summary>Generated LLRP enumeration 'GetReaderConfigRequestedData'.</summary>
public enum GetReaderConfigRequestedData : long
{
    All = 0L,
    Identification = 1L,
    AntennaProperties = 2L,
    AntennaConfiguration = 3L,
    ROReportSpec = 4L,
    ReaderEventNotificationSpec = 5L,
    AccessReportSpec = 6L,
    LLRPConfigurationStateValue = 7L,
    KeepaliveSpec = 8L,
    GPIPortCurrentState = 9L,
    GPOWriteData = 10L,
    EventsAndReports = 11L,
}
