// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Enumerations.V1_1;

/// <summary>Generated LLRP enumeration 'C1G2TagInventoryStateAwareS'.</summary>
public enum C1G2TagInventoryStateAwareS : long
{
    SL = 0L,
    Not_SL = 1L,
}
