// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Enumerations.V1_1;

/// <summary>Generated LLRP enumeration 'C1G2KillResultType'.</summary>
public enum C1G2KillResultType : long
{
    Success = 0L,
    Zero_Kill_Password_Error = 1L,
    Insufficient_Power = 2L,
    Nonspecific_Tag_Error = 3L,
    No_Response_From_Tag = 4L,
    Nonspecific_Reader_Error = 5L,
}
