// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Enumerations.V1_1;

/// <summary>Generated LLRP enumeration 'C1G2BlockPermalockResultType'.</summary>
public enum C1G2BlockPermalockResultType : long
{
    Success = 0L,
    Insufficient_Power_To_Perform_Block_Permalock_Operation = 1L,
    Nonspecific_Tag_Error = 2L,
    No_Response_From_Tag = 3L,
    Nonspecific_Reader_Error = 4L,
    Incorrect_Password_Error = 5L,
    Tag_Memory_Overrun_Error = 6L,
}
