// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'MotoAutonomousCapabilities'.</summary>
/// <param name="Version">Wire field 'Version' (U32).</param>
/// <param name="CanSupportAutonomousMode">Wire field 'CanSupportAutonomousMode' (U1).</param>
public sealed record MotoAutonomousCapabilities(
    uint Version,
    bool CanSupportAutonomousMode
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 161U;
    public const uint Subtype = 100U;
}
