// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'MotoTagEventsGenerationCapabilities'.</summary>
/// <param name="Version">Wire field 'Version' (U32).</param>
/// <param name="CanSelectTagEvents">Wire field 'CanSelectTagEvents' (U1).</param>
/// <param name="CanSelectTagReportingFormat">Wire field 'CanSelectTagReportingFormat' (U1).</param>
/// <param name="CanSelectMovingEvent">Wire field 'CanSelectMovingEvent' (U1).</param>
public sealed record MotoTagEventsGenerationCapabilities(
    uint Version,
    bool CanSelectTagEvents,
    bool CanSelectTagReportingFormat,
    bool CanSelectMovingEvent
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 161U;
    public const uint Subtype = 120U;
}
