// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'MotoPersistenceCapabilities'.</summary>
/// <param name="Version">Wire field 'Version' (U32).</param>
/// <param name="CanSaveConfiguration">Wire field 'CanSaveConfiguration' (U1).</param>
/// <param name="CanSaveTags">Wire field 'CanSaveTags' (U1).</param>
/// <param name="CanSaveEvents">Wire field 'CanSaveEvents' (U1).</param>
public sealed record MotoPersistenceCapabilities(
    uint Version,
    bool CanSaveConfiguration,
    bool CanSaveTags,
    bool CanSaveEvents
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 161U;
    public const uint Subtype = 300U;
}
