// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'MotoPersistenceSaveParams'.</summary>
/// <param name="SaveConfiguration">Wire field 'SaveConfiguration' (U1).</param>
/// <param name="SaveTagData">Wire field 'SaveTagData' (U1).</param>
/// <param name="SaveTagEventData">Wire field 'SaveTagEventData' (U1).</param>
public sealed record MotoPersistenceSaveParams(
    bool SaveConfiguration,
    bool SaveTagData,
    bool SaveTagEventData
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 161U;
    public const uint Subtype = 350U;
}
