// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'MotoCustomCommandOptions'.</summary>
/// <param name="EnableNXPSetAndResetQuietCommands">Wire field 'EnableNXPSetAndResetQuietCommands' (U1).</param>
public sealed record MotoCustomCommandOptions(
    bool EnableNXPSetAndResetQuietCommands
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 161U;
    public const uint Subtype = 466U;
}
