// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'MotoDefaultSpec'.</summary>
/// <param name="UseDefaultSpecForAutoMode">Wire field 'UseDefaultSpecForAutoMode' (U1).</param>
/// <param name="ROSpec">LLRP parameter 'ROSpec' with cardinality 1..1.</param>
/// <param name="AccessSpecItems">LLRP parameter 'AccessSpec' with cardinality 0..N.</param>
public sealed record MotoDefaultSpec(
    bool UseDefaultSpecForAutoMode,
    global::LlrpNet.Protocol.Parameters.V1_0_1.ROSpec ROSpec,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.V1_0_1.AccessSpec> AccessSpecItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 161U;
    public const uint Subtype = 102U;
}
