// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'MotoFilterTagList'.</summary>
/// <param name="Match">Wire field 'Match' (U8).</param>
/// <param name="EPCDataItems">LLRP parameter 'EPCData' with cardinality 1..N.</param>
public sealed record MotoFilterTagList(
    byte Match,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.V1_0_1.EPCData> EPCDataItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 161U;
    public const uint Subtype = 258U;
}
