// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'MotoTagEventSelector'.</summary>
/// <param name="ReportNewTagEvent">Wire field 'ReportNewTagEvent' (U8).</param>
/// <param name="NewTagEventModeratedTimeout">Wire field 'NewTagEventModeratedTimeout' (U16).</param>
/// <param name="ReportTagInvisibleEvent">Wire field 'ReportTagInvisibleEvent' (U8).</param>
/// <param name="TagInvisibleEventModeratedTimeout">Wire field 'TagInvisibleEventModeratedTimeout' (U16).</param>
/// <param name="ReportTagVisibilityChangeEvent">Wire field 'ReportTagVisibilityChangeEvent' (U8).</param>
/// <param name="TagVisibilityChangeEventModeratedTimeout">Wire field 'TagVisibilityChangeEventModeratedTimeout' (U16).</param>
public sealed record MotoTagEventSelector(
    byte ReportNewTagEvent,
    ushort NewTagEventModeratedTimeout,
    byte ReportTagInvisibleEvent,
    ushort TagInvisibleEventModeratedTimeout,
    byte ReportTagVisibilityChangeEvent,
    ushort TagVisibilityChangeEventModeratedTimeout
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 161U;
    public const uint Subtype = 121U;
}
