// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'MotoAntennaStopCondition'.</summary>
/// <param name="AntennaStopTrigger">Wire field 'AntennaStopTrigger' (U8).</param>
/// <param name="AntennaStopConditionValue">Wire field 'AntennaStopConditionValue' (U16).</param>
public sealed record MotoAntennaStopCondition(
    byte AntennaStopTrigger,
    ushort AntennaStopConditionValue
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 161U;
    public const uint Subtype = 704U;
}
