// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'MotoTagReportContentSelector'.</summary>
/// <param name="EnableZoneID">Wire field 'EnableZoneID' (U1).</param>
/// <param name="EnableZoneName">Wire field 'EnableZoneName' (U1).</param>
/// <param name="EnableAntennaPhysicalPortConfig">Wire field 'EnableAntennaPhysicalPortConfig' (U1).</param>
/// <param name="EnablePhase">Wire field 'EnablePhase' (U1).</param>
/// <param name="EnableGPS">Wire field 'EnableGPS' (U1).</param>
/// <param name="EnableMLTReport">Wire field 'EnableMLTReport' (U1).</param>
public sealed record MotoTagReportContentSelector(
    bool EnableZoneID,
    bool EnableZoneName,
    bool EnableAntennaPhysicalPortConfig,
    bool EnablePhase,
    bool EnableGPS,
    bool EnableMLTReport
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 161U;
    public const uint Subtype = 708U;
}
