// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'MotoNXPEASAlarmNotification'.</summary>
/// <param name="EASAlarmCode">Wire field 'EASAlarmCode' (U64).</param>
/// <param name="AntennaID">LLRP parameter 'AntennaID' with cardinality 0..1.</param>
public sealed record MotoNXPEASAlarmNotification(
    ulong EASAlarmCode,
    global::LlrpNet.Protocol.Parameters.V1_0_1.AntennaID? AntennaID
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 161U;
    public const uint Subtype = 464U;
}
