// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'MotoConnectionFailureReason'.</summary>
/// <param name="ErrorCode">Wire field 'ErrorCode' (U8).</param>
/// <param name="ErrorDescription">Wire field 'ErrorDescription' (Utf8Vector).</param>
public sealed record MotoConnectionFailureReason(
    byte ErrorCode,
    string ErrorDescription
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 161U;
    public const uint Subtype = 465U;
}
