// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'MotoC1G2BlockPermalock'.</summary>
/// <param name="OpSpecID">Wire field 'OpSpecID' (U16).</param>
/// <param name="AccessPassword">Wire field 'AccessPassword' (U32).</param>
/// <param name="MB">Wire field 'MB' (U2).</param>
/// <param name="ReadLock">Wire field 'ReadLock' (U1).</param>
/// <param name="BlockPointer">Wire field 'BlockPointer' (U16).</param>
/// <param name="ReadBlockRange">Wire field 'ReadBlockRange' (U16).</param>
/// <param name="Mask">Wire field 'Mask' (U16Vector).</param>
public sealed record MotoC1G2BlockPermalock(
    ushort OpSpecID,
    uint AccessPassword,
    byte MB,
    bool ReadLock,
    ushort BlockPointer,
    ushort ReadBlockRange,
    global::System.Collections.Generic.IReadOnlyList<ushort> Mask
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 161U;
    public const uint Subtype = 453U;
}
