// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'MotoNXPChangeConfig'.</summary>
/// <param name="OpSpecID">Wire field 'OpSpecID' (U16).</param>
/// <param name="AccessPassword">Wire field 'AccessPassword' (U32).</param>
/// <param name="NXPChangeConfigWord">Wire field 'NXPChangeConfigWord' (U16).</param>
public sealed record MotoNXPChangeConfig(
    ushort OpSpecID,
    uint AccessPassword,
    ushort NXPChangeConfigWord
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 161U;
    public const uint Subtype = 485U;
}
