// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'MotoC1G2UntraceableOpSpecResult'.</summary>
/// <param name="Result">Wire field 'Result' (U8).</param>
/// <param name="OpSpecID">Wire field 'OpSpecID' (U16).</param>
/// <param name="DataBits">Wire field 'DataBits' (U1Vector).</param>
public sealed record MotoC1G2UntraceableOpSpecResult(
    byte Result,
    ushort OpSpecID,
    global::System.Collections.Generic.IReadOnlyList<bool> DataBits
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 161U;
    public const uint Subtype = 495U;
}
