// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ZebraROSpecStartTrigger'.</summary>
/// <param name="ZebraTimelapseStart">LLRP parameter 'ZebraTimelapseStart' with cardinality 0..1.</param>
/// <param name="ZebraDistance">LLRP parameter 'ZebraDistance' with cardinality 0..1.</param>
public sealed record ZebraROSpecStartTrigger(
    global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.ZebraTimelapseStart? ZebraTimelapseStart,
    global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.ZebraDistance? ZebraDistance
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 161U;
    public const uint Subtype = 802U;
}
