// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ZebraDistance'.</summary>
/// <param name="Value">Wire field 'Value' (U32).</param>
public sealed record ZebraDistance(
    uint Value
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 161U;
    public const uint Subtype = 804U;
}
