// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ZebraROSpecStopTrigger'.</summary>
/// <param name="ZebraTimelapseStop">LLRP parameter 'ZebraTimelapseStop' with cardinality 0..1.</param>
public sealed record ZebraROSpecStopTrigger(
    global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.ZebraTimelapseStop? ZebraTimelapseStop
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 161U;
    public const uint Subtype = 805U;
}
