// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V2_0;

internal sealed class RFSurveySpecStopTriggerCodec : global::LlrpNet.Protocol.Codecs.LlrpParameterCodec<global::LlrpNet.Protocol.Parameters.V2_0.RFSurveySpecStopTrigger>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public RFSurveySpecStopTriggerCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Parameters.V2_0.RFSurveySpecStopTrigger Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 3);
        var reader = new GeneratedWireReader(payload);
        int offset = 0;
        global::LlrpNet.Protocol.Enumerations.V2_0.RFSurveySpecStopTriggerType StopTriggerType = GeneratedCodecRuntime.ReadEnum<global::LlrpNet.Protocol.Enumerations.V2_0.RFSurveySpecStopTriggerType>(reader.ReadByte());
        uint DurationPeriod = reader.ReadUInt32();
        uint N = reader.ReadUInt32();
        offset += reader.BytePosition;
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Parameters.V2_0.RFSurveySpecStopTrigger(
            StopTriggerType,
            DurationPeriod,
            N);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V2_0.RFSurveySpecStopTrigger parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 3);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 9;
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V2_0.RFSurveySpecStopTrigger parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        GeneratedCodecRuntime.ValidateEnum(parameter.StopTriggerType, "StopTriggerType"); wireWriter.WriteByte(checked((byte)global::System.Convert.ToUInt64(parameter.StopTriggerType, global::System.Globalization.CultureInfo.InvariantCulture)));
        wireWriter.WriteUInt32(parameter.DurationPeriod);
        wireWriter.WriteUInt32(parameter.N);
        offset += wireWriter.BytePosition;
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
