// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V2_0;

internal sealed class FieldErrorCodec : global::LlrpNet.Protocol.Codecs.LlrpParameterCodec<global::LlrpNet.Protocol.Parameters.V2_0.FieldError>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public FieldErrorCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Parameters.V2_0.FieldError Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 3);
        var reader = new GeneratedWireReader(payload);
        int offset = 0;
        ushort FieldNum = reader.ReadUInt16();
        global::LlrpNet.Protocol.Enumerations.V2_0.StatusCode ErrorCode = GeneratedCodecRuntime.ReadEnum<global::LlrpNet.Protocol.Enumerations.V2_0.StatusCode>(reader.ReadUInt16());
        offset += reader.BytePosition;
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Parameters.V2_0.FieldError(
            FieldNum,
            ErrorCode);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V2_0.FieldError parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 3);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 4;
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V2_0.FieldError parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteUInt16(parameter.FieldNum);
        GeneratedCodecRuntime.ValidateEnum(parameter.ErrorCode, "ErrorCode"); wireWriter.WriteUInt16(checked((ushort)global::System.Convert.ToUInt64(parameter.ErrorCode, global::System.Globalization.CultureInfo.InvariantCulture)));
        offset += wireWriter.BytePosition;
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
