// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V2_0;

internal sealed class C1G2ReadBufferCodec : global::LlrpNet.Protocol.Codecs.LlrpParameterCodec<global::LlrpNet.Protocol.Parameters.V2_0.C1G2ReadBuffer>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public C1G2ReadBufferCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Parameters.V2_0.C1G2ReadBuffer Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 3);
        var reader = new GeneratedWireReader(payload);
        int offset = 0;
        ushort OpSpecID = reader.ReadUInt16();
        uint AccessPassword = reader.ReadUInt32();
        ushort WordPtr = reader.ReadUInt16();
        ushort NumBits = reader.ReadUInt16();
        offset += reader.BytePosition;
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Parameters.V2_0.C1G2ReadBuffer(
            OpSpecID,
            AccessPassword,
            WordPtr,
            NumBits);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V2_0.C1G2ReadBuffer parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 3);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 10;
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V2_0.C1G2ReadBuffer parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteUInt16(parameter.OpSpecID);
        wireWriter.WriteUInt32(parameter.AccessPassword);
        wireWriter.WriteUInt16(parameter.WordPtr);
        wireWriter.WriteUInt16(parameter.NumBits);
        offset += wireWriter.BytePosition;
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
