// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V2_0;

internal sealed class C1G2TagPrivilegeCodec : global::LlrpNet.Protocol.Codecs.LlrpParameterCodec<global::LlrpNet.Protocol.Parameters.V2_0.C1G2TagPrivilege>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public C1G2TagPrivilegeCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Parameters.V2_0.C1G2TagPrivilege Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 3);
        var reader = new GeneratedWireReader(payload);
        int offset = 0;
        ushort OpSpecID = reader.ReadUInt16();
        uint AccessPassword = reader.ReadUInt32();
        bool S = reader.ReadBoolean();
        bool L = reader.ReadBoolean();
        bool A = reader.ReadBoolean();
        bool T = reader.ReadBoolean();
        reader.ReadReservedBits(4);
        ushort KeyID = reader.ReadUInt16();
        ushort Privilege = reader.ReadUInt16();
        offset += reader.BytePosition;
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Parameters.V2_0.C1G2TagPrivilege(
            OpSpecID,
            AccessPassword,
            S,
            L,
            A,
            T,
            KeyID,
            Privilege);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V2_0.C1G2TagPrivilege parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 3);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 11;
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V2_0.C1G2TagPrivilege parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteUInt16(parameter.OpSpecID);
        wireWriter.WriteUInt32(parameter.AccessPassword);
        wireWriter.WriteBoolean(parameter.S);
        wireWriter.WriteBoolean(parameter.L);
        wireWriter.WriteBoolean(parameter.A);
        wireWriter.WriteBoolean(parameter.T);
        wireWriter.WriteReservedBits(4);
        wireWriter.WriteUInt16(parameter.KeyID);
        wireWriter.WriteUInt16(parameter.Privilege);
        offset += wireWriter.BytePosition;
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
