// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V2_0;

internal sealed class C1G2ReadBufferOpSpecResultCodec : global::LlrpNet.Protocol.Codecs.LlrpParameterCodec<global::LlrpNet.Protocol.Parameters.V2_0.C1G2ReadBufferOpSpecResult>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public C1G2ReadBufferOpSpecResultCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Parameters.V2_0.C1G2ReadBufferOpSpecResult Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 3);
        var reader = new GeneratedWireReader(payload);
        int offset = 0;
        byte Result = reader.ReadByte();
        ushort OpSpecID = reader.ReadUInt16();
        ushort RespBitLen = reader.ReadUInt16();
        global::System.Collections.Generic.IReadOnlyList<bool> Response = reader.ReadBitVector();
        offset += reader.BytePosition;
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Parameters.V2_0.C1G2ReadBufferOpSpecResult(
            Result,
            OpSpecID,
            RespBitLen,
            Response);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V2_0.C1G2ReadBufferOpSpecResult parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 3);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 5;
        length = checked(length + GeneratedCodecRuntime.GetBitVectorLength(parameter.Response));
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V2_0.C1G2ReadBufferOpSpecResult parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteByte(parameter.Result);
        wireWriter.WriteUInt16(parameter.OpSpecID);
        wireWriter.WriteUInt16(parameter.RespBitLen);
        wireWriter.WriteBitVector(parameter.Response);
        offset += wireWriter.BytePosition;
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
