// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V1_1;

internal sealed class ROSpecCodec : global::LlrpNet.Protocol.Codecs.LlrpParameterCodec<global::LlrpNet.Protocol.Parameters.V1_1.ROSpec>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public ROSpecCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Parameters.V1_1.ROSpec Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 2);
        var reader = new GeneratedWireReader(payload);
        int offset = 0;
        uint ROSpecID = reader.ReadUInt32();
        byte Priority = reader.ReadByte();
        global::LlrpNet.Protocol.Enumerations.V1_1.ROSpecState CurrentState = GeneratedCodecRuntime.ReadEnum<global::LlrpNet.Protocol.Enumerations.V1_1.ROSpecState>(reader.ReadByte());
        offset += reader.BytePosition;
        global::LlrpNet.Protocol.Parameters.V1_1.ROBoundarySpec? ROBoundarySpec = null;
        if (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 178, false, 0U, 0U))
        {
            ROBoundarySpec = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_1.ROBoundarySpec>(registry, version, payload, ref offset);
        }
        if (ROBoundarySpec is null)
        {
            throw GeneratedCodecRuntime.InvalidSequence("Required parameter 'ROBoundarySpec' is missing.");
        }
        reader = new GeneratedWireReader(payload[offset..]);
        var SpecParameterItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Parameters.ILlrpParameter>();
        while (offset < payload.Length && (GeneratedCodecRuntime.IsNextParameter(payload[offset..], 183, false, 0U, 0U) || GeneratedCodecRuntime.IsNextParameter(payload[offset..], 187, false, 0U, 0U) || GeneratedCodecRuntime.IsNextParameter(payload[offset..], 355, false, 0U, 0U) || GeneratedCodecRuntime.IsNextParameter(payload[offset..], 1023, false, 0U, 0U)))
        {
            SpecParameterItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.ILlrpParameter>(registry, version, payload, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(SpecParameterItems.Count, 1, "SpecParameterItems");
        reader = new GeneratedWireReader(payload[offset..]);
        global::LlrpNet.Protocol.Parameters.V1_1.ROReportSpec? ROReportSpec = null;
        if (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 237, false, 0U, 0U))
        {
            ROReportSpec = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_1.ROReportSpec>(registry, version, payload, ref offset);
        }
        reader = new GeneratedWireReader(payload[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Parameters.V1_1.ROSpec(
            ROSpecID,
            Priority,
            CurrentState,
            ROBoundarySpec!,
            SpecParameterItems,
            ROReportSpec);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_1.ROSpec parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 2);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 6;
        if (parameter.ROBoundarySpec is null)
        {
            throw new global::System.ArgumentNullException("ROBoundarySpec");
        }
        GeneratedCodecRuntime.ValidateParameterMatch(parameter.ROBoundarySpec!, "ROBoundarySpec", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.ROBoundarySpec!, 178, false, 0U, 0U));
        length = checked(length + registry.GetEncodedParameterLength(version, parameter.ROBoundarySpec!));
        if (parameter.SpecParameterItems is null)
        {
            throw new global::System.ArgumentNullException("SpecParameterItems");
        }
        if (parameter.SpecParameterItems.Count < 1)
        {
            throw new global::System.ArgumentException("Member 'SpecParameterItems' requires cardinality 1..N.", "SpecParameterItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.SpecParameterItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "SpecParameterItems", (GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 183, false, 0U, 0U) || GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 187, false, 0U, 0U) || GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 355, false, 0U, 0U) || GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 1023, false, 0U, 0U)));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        if (parameter.ROReportSpec is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.ROReportSpec, "ROReportSpec", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.ROReportSpec, 237, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.ROReportSpec));
        }
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_1.ROSpec parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteUInt32(parameter.ROSpecID);
        wireWriter.WriteByte(parameter.Priority);
        GeneratedCodecRuntime.ValidateEnum(parameter.CurrentState, "CurrentState"); wireWriter.WriteByte(checked((byte)global::System.Convert.ToUInt64(parameter.CurrentState, global::System.Globalization.CultureInfo.InvariantCulture)));
        offset += wireWriter.BytePosition;
        offset += registry.EncodeParameter(version, parameter.ROBoundarySpec!, destination[offset..]);
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.SpecParameterItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (parameter.ROReportSpec is not null)
        {
            offset += registry.EncodeParameter(version, parameter.ROReportSpec, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
