// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V1_1;

internal sealed class TagReportContentSelectorCodec : global::LlrpNet.Protocol.Codecs.LlrpParameterCodec<global::LlrpNet.Protocol.Parameters.V1_1.TagReportContentSelector>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public TagReportContentSelectorCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Parameters.V1_1.TagReportContentSelector Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 2);
        var reader = new GeneratedWireReader(payload);
        int offset = 0;
        bool EnableROSpecID = reader.ReadBoolean();
        bool EnableSpecIndex = reader.ReadBoolean();
        bool EnableInventoryParameterSpecID = reader.ReadBoolean();
        bool EnableAntennaID = reader.ReadBoolean();
        bool EnableChannelIndex = reader.ReadBoolean();
        bool EnablePeakRSSI = reader.ReadBoolean();
        bool EnableFirstSeenTimestamp = reader.ReadBoolean();
        bool EnableLastSeenTimestamp = reader.ReadBoolean();
        bool EnableTagSeenCount = reader.ReadBoolean();
        bool EnableAccessSpecID = reader.ReadBoolean();
        reader.ReadReservedBits(6);
        offset += reader.BytePosition;
        var AirProtocolEPCMemorySelectorItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Choices.V1_1.IAirProtocolEPCMemorySelector>();
        while (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 348, false, 0U, 0U))
        {
            AirProtocolEPCMemorySelectorItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Choices.V1_1.IAirProtocolEPCMemorySelector>(registry, version, payload, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(AirProtocolEPCMemorySelectorItems.Count, 0, "AirProtocolEPCMemorySelectorItems");
        reader = new GeneratedWireReader(payload[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Parameters.V1_1.TagReportContentSelector(
            EnableROSpecID,
            EnableSpecIndex,
            EnableInventoryParameterSpecID,
            EnableAntennaID,
            EnableChannelIndex,
            EnablePeakRSSI,
            EnableFirstSeenTimestamp,
            EnableLastSeenTimestamp,
            EnableTagSeenCount,
            EnableAccessSpecID,
            AirProtocolEPCMemorySelectorItems);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_1.TagReportContentSelector parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 2);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 2;
        if (parameter.AirProtocolEPCMemorySelectorItems is null)
        {
            throw new global::System.ArgumentNullException("AirProtocolEPCMemorySelectorItems");
        }
        if (parameter.AirProtocolEPCMemorySelectorItems.Count < 0)
        {
            throw new global::System.ArgumentException("Member 'AirProtocolEPCMemorySelectorItems' requires cardinality 0..N.", "AirProtocolEPCMemorySelectorItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.AirProtocolEPCMemorySelectorItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "AirProtocolEPCMemorySelectorItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 348, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_1.TagReportContentSelector parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteBoolean(parameter.EnableROSpecID);
        wireWriter.WriteBoolean(parameter.EnableSpecIndex);
        wireWriter.WriteBoolean(parameter.EnableInventoryParameterSpecID);
        wireWriter.WriteBoolean(parameter.EnableAntennaID);
        wireWriter.WriteBoolean(parameter.EnableChannelIndex);
        wireWriter.WriteBoolean(parameter.EnablePeakRSSI);
        wireWriter.WriteBoolean(parameter.EnableFirstSeenTimestamp);
        wireWriter.WriteBoolean(parameter.EnableLastSeenTimestamp);
        wireWriter.WriteBoolean(parameter.EnableTagSeenCount);
        wireWriter.WriteBoolean(parameter.EnableAccessSpecID);
        wireWriter.WriteReservedBits(6);
        offset += wireWriter.BytePosition;
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.AirProtocolEPCMemorySelectorItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
