// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V1_1;

internal sealed class ROSpecEventCodec : global::LlrpNet.Protocol.Codecs.LlrpParameterCodec<global::LlrpNet.Protocol.Parameters.V1_1.ROSpecEvent>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public ROSpecEventCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Parameters.V1_1.ROSpecEvent Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 2);
        var reader = new GeneratedWireReader(payload);
        int offset = 0;
        global::LlrpNet.Protocol.Enumerations.V1_1.ROSpecEventType EventType = GeneratedCodecRuntime.ReadEnum<global::LlrpNet.Protocol.Enumerations.V1_1.ROSpecEventType>(reader.ReadByte());
        uint ROSpecID = reader.ReadUInt32();
        uint PreemptingROSpecID = reader.ReadUInt32();
        offset += reader.BytePosition;
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Parameters.V1_1.ROSpecEvent(
            EventType,
            ROSpecID,
            PreemptingROSpecID);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_1.ROSpecEvent parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 2);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 9;
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_1.ROSpecEvent parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        GeneratedCodecRuntime.ValidateEnum(parameter.EventType, "EventType"); wireWriter.WriteByte(checked((byte)global::System.Convert.ToUInt64(parameter.EventType, global::System.Globalization.CultureInfo.InvariantCulture)));
        wireWriter.WriteUInt32(parameter.ROSpecID);
        wireWriter.WriteUInt32(parameter.PreemptingROSpecID);
        offset += wireWriter.BytePosition;
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
