// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V1_1;

internal sealed class ConnectionAttemptEventCodec : global::LlrpNet.Protocol.Codecs.LlrpParameterCodec<global::LlrpNet.Protocol.Parameters.V1_1.ConnectionAttemptEvent>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public ConnectionAttemptEventCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Parameters.V1_1.ConnectionAttemptEvent Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 2);
        var reader = new GeneratedWireReader(payload);
        int offset = 0;
        global::LlrpNet.Protocol.Enumerations.V1_1.ConnectionAttemptStatusType Status = GeneratedCodecRuntime.ReadEnum<global::LlrpNet.Protocol.Enumerations.V1_1.ConnectionAttemptStatusType>(reader.ReadUInt16());
        offset += reader.BytePosition;
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Parameters.V1_1.ConnectionAttemptEvent(
            Status);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_1.ConnectionAttemptEvent parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 2);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 2;
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_1.ConnectionAttemptEvent parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        GeneratedCodecRuntime.ValidateEnum(parameter.Status, "Status"); wireWriter.WriteUInt16(checked((ushort)global::System.Convert.ToUInt64(parameter.Status, global::System.Globalization.CultureInfo.InvariantCulture)));
        offset += wireWriter.BytePosition;
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
