// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V1_1;

internal sealed class C1G2LockCodec : global::LlrpNet.Protocol.Codecs.LlrpParameterCodec<global::LlrpNet.Protocol.Parameters.V1_1.C1G2Lock>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public C1G2LockCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Parameters.V1_1.C1G2Lock Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 2);
        var reader = new GeneratedWireReader(payload);
        int offset = 0;
        ushort OpSpecID = reader.ReadUInt16();
        uint AccessPassword = reader.ReadUInt32();
        offset += reader.BytePosition;
        var C1G2LockPayloadItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Parameters.V1_1.C1G2LockPayload>();
        while (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 345, false, 0U, 0U))
        {
            C1G2LockPayloadItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_1.C1G2LockPayload>(registry, version, payload, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(C1G2LockPayloadItems.Count, 1, "C1G2LockPayloadItems");
        reader = new GeneratedWireReader(payload[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Parameters.V1_1.C1G2Lock(
            OpSpecID,
            AccessPassword,
            C1G2LockPayloadItems);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_1.C1G2Lock parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 2);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 6;
        if (parameter.C1G2LockPayloadItems is null)
        {
            throw new global::System.ArgumentNullException("C1G2LockPayloadItems");
        }
        if (parameter.C1G2LockPayloadItems.Count < 1)
        {
            throw new global::System.ArgumentException("Member 'C1G2LockPayloadItems' requires cardinality 1..N.", "C1G2LockPayloadItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.C1G2LockPayloadItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "C1G2LockPayloadItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 345, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_1.C1G2Lock parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteUInt16(parameter.OpSpecID);
        wireWriter.WriteUInt32(parameter.AccessPassword);
        offset += wireWriter.BytePosition;
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.C1G2LockPayloadItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
