// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V1_1;

internal sealed class C1G2RecommissionCodec : global::LlrpNet.Protocol.Codecs.LlrpParameterCodec<global::LlrpNet.Protocol.Parameters.V1_1.C1G2Recommission>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public C1G2RecommissionCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Parameters.V1_1.C1G2Recommission Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 2);
        var reader = new GeneratedWireReader(payload);
        int offset = 0;
        ushort OpSpecID = reader.ReadUInt16();
        uint KillPassword = reader.ReadUInt32();
        reader.ReadReservedBits(5);
        bool ThreeSB = reader.ReadBoolean();
        bool TwoSB = reader.ReadBoolean();
        bool LSB = reader.ReadBoolean();
        offset += reader.BytePosition;
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Parameters.V1_1.C1G2Recommission(
            OpSpecID,
            KillPassword,
            ThreeSB,
            TwoSB,
            LSB);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_1.C1G2Recommission parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 2);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 7;
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_1.C1G2Recommission parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteUInt16(parameter.OpSpecID);
        wireWriter.WriteUInt32(parameter.KillPassword);
        wireWriter.WriteReservedBits(5);
        wireWriter.WriteBoolean(parameter.ThreeSB);
        wireWriter.WriteBoolean(parameter.TwoSB);
        wireWriter.WriteBoolean(parameter.LSB);
        offset += wireWriter.BytePosition;
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
