// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V1_1;

internal sealed class GET_SUPPORTED_VERSION_RESPONSECodec : global::LlrpNet.Protocol.Codecs.LlrpMessageCodec<global::LlrpNet.Protocol.Messages.V1_1.GET_SUPPORTED_VERSION_RESPONSE>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public GET_SUPPORTED_VERSION_RESPONSECodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Messages.V1_1.GET_SUPPORTED_VERSION_RESPONSE Decode(
        global::LlrpNet.Core.Protocol.LlrpMessageHeader header,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(header.Version, 2);
        var version = header.Version;
        var reader = new GeneratedWireReader(payload);
        int offset = 0;
        global::LlrpNet.Protocol.Parameters.V1_1.LLRPStatus? LLRPStatus = null;
        if (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 287, false, 0U, 0U))
        {
            LLRPStatus = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_1.LLRPStatus>(registry, version, payload, ref offset);
        }
        if (LLRPStatus is null)
        {
            throw GeneratedCodecRuntime.InvalidSequence("Required parameter 'LLRPStatus' is missing.");
        }
        reader = new GeneratedWireReader(payload[offset..]);
        byte CurrentVersion = reader.ReadByte();
        byte SupportedVersion = reader.ReadByte();
        offset += reader.BytePosition;
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Messages.V1_1.GET_SUPPORTED_VERSION_RESPONSE(
            header.MessageId,
            LLRPStatus!,
            CurrentVersion,
            SupportedVersion);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Messages.V1_1.GET_SUPPORTED_VERSION_RESPONSE message)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 2);
        global::System.ArgumentNullException.ThrowIfNull(message);
        int length = 2;
        if (message.LLRPStatus is null)
        {
            throw new global::System.ArgumentNullException("LLRPStatus");
        }
        GeneratedCodecRuntime.ValidateParameterMatch(message.LLRPStatus!, "LLRPStatus", GeneratedCodecRuntime.IsParameterMatch(registry, version, message.LLRPStatus!, 287, false, 0U, 0U));
        length = checked(length + registry.GetEncodedParameterLength(version, message.LLRPStatus!));
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Messages.V1_1.GET_SUPPORTED_VERSION_RESPONSE message,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, message);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        offset += registry.EncodeParameter(version, message.LLRPStatus!, destination[offset..]);
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        wireWriter.WriteByte(message.CurrentVersion);
        wireWriter.WriteByte(message.SupportedVersion);
        offset += wireWriter.BytePosition;
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
