// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Choices.V1_0_1;

/// <summary>Marks a parameter accepted by the LLRP choice 'AirProtocolOpSpec'.</summary>
public interface IAirProtocolOpSpec : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
}
