// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Enumerations.V2_0;

/// <summary>Generated LLRP enumeration 'AISpecStopTriggerType'.</summary>
public enum AISpecStopTriggerType : long
{
    Null = 0L,
    Duration = 1L,
    GPI_With_Timeout = 2L,
    Tag_Observation = 3L,
}
