// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Enumerations.V2_0;

/// <summary>Generated LLRP enumeration 'RFSurveyEventType'.</summary>
public enum RFSurveyEventType : long
{
    Start_Of_RFSurvey = 0L,
    End_Of_RFSurvey = 1L,
}
