// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Enumerations.V2_0;

/// <summary>Generated LLRP enumeration 'AISpecEventType'.</summary>
public enum AISpecEventType : long
{
    End_Of_AISpec = 0L,
}
