// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Enumerations.V2_0;

/// <summary>Generated LLRP enumeration 'AntennaEventType'.</summary>
public enum AntennaEventType : long
{
    Antenna_Disconnected = 0L,
    Antenna_Connected = 1L,
}
