// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Impinj.Enumerations.V1_0_1;

/// <summary>Generated LLRP custom enumeration 'ImpinjReportBufferMode'.</summary>
public enum ImpinjReportBufferMode : long
{
    Normal = 0L,
    Low_Latency = 1L,
}
