// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Impinj.Enumerations.V1_0_1;

/// <summary>Generated LLRP custom enumeration 'ImpinjOptimizedReadMode'.</summary>
public enum ImpinjOptimizedReadMode : long
{
    Disabled = 0L,
    Enabled = 1L,
}
