// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Impinj.Enumerations.V1_0_1;

/// <summary>Generated LLRP custom enumeration 'ImpinjAccessSpecOrderingMode'.</summary>
public enum ImpinjAccessSpecOrderingMode : long
{
    FIFO = 0L,
    Ascending = 1L,
}
