// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Codecs.V1_0_1;

internal sealed class MotoC1G2LLRPCapabilitiesCodec : global::LlrpNet.Protocol.Codecs.LlrpCustomParameterCodec<global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoC1G2LLRPCapabilities>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public MotoC1G2LLRPCapabilitiesCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoC1G2LLRPCapabilities Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> data)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(data);
        int offset = 0;
        uint Version = reader.ReadUInt32();
        bool CanSupportBlockPermalock = reader.ReadBoolean();
        bool CanSupportRecommissioning = reader.ReadBoolean();
        bool CanWriteUMI = reader.ReadBoolean();
        bool CanSupportNXPCuxtomCommands = reader.ReadBoolean();
        bool CanSupportFujitsuCuxtomCommands = reader.ReadBoolean();
        bool CanSupportG2V2Commands = reader.ReadBoolean();
        bool DeviceSetCapabilityBit1 = reader.ReadBoolean();
        reader.ReadReservedBits(1);
        offset += reader.BytePosition;
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, data.Length);
        return new global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoC1G2LLRPCapabilities(
            Version,
            CanSupportBlockPermalock,
            CanSupportRecommissioning,
            CanWriteUMI,
            CanSupportNXPCuxtomCommands,
            CanSupportFujitsuCuxtomCommands,
            CanSupportG2V2Commands,
            DeviceSetCapabilityBit1);
    }

    public override int GetEncodedDataLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoC1G2LLRPCapabilities parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 5;
        return length;
    }

    public override int EncodeData(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoC1G2LLRPCapabilities parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedDataLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteUInt32(parameter.Version);
        wireWriter.WriteBoolean(parameter.CanSupportBlockPermalock);
        wireWriter.WriteBoolean(parameter.CanSupportRecommissioning);
        wireWriter.WriteBoolean(parameter.CanWriteUMI);
        wireWriter.WriteBoolean(parameter.CanSupportNXPCuxtomCommands);
        wireWriter.WriteBoolean(parameter.CanSupportFujitsuCuxtomCommands);
        wireWriter.WriteBoolean(parameter.CanSupportG2V2Commands);
        wireWriter.WriteBoolean(parameter.DeviceSetCapabilityBit1);
        wireWriter.WriteReservedBits(1);
        offset += wireWriter.BytePosition;
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
