// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Codecs.V1_0_1;

internal sealed class MotoVersionCodec : global::LlrpNet.Protocol.Codecs.LlrpCustomParameterCodec<global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoVersion>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public MotoVersionCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoVersion Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> data)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(data);
        int offset = 0;
        string ModuleName = reader.ReadUtf8();
        string ModuleVersion = reader.ReadUtf8();
        offset += reader.BytePosition;
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, data.Length);
        return new global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoVersion(
            ModuleName,
            ModuleVersion);
    }

    public override int GetEncodedDataLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoVersion parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 0;
        length = checked(length + GeneratedCodecRuntime.GetUtf8Length(parameter.ModuleName));
        length = checked(length + GeneratedCodecRuntime.GetUtf8Length(parameter.ModuleVersion));
        return length;
    }

    public override int EncodeData(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoVersion parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedDataLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteUtf8(parameter.ModuleName);
        wireWriter.WriteUtf8(parameter.ModuleVersion);
        offset += wireWriter.BytePosition;
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
