// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Codecs.V1_0_1;

internal sealed class MotoVersionListCodec : global::LlrpNet.Protocol.Codecs.LlrpCustomParameterCodec<global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoVersionList>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public MotoVersionListCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoVersionList Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> data)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(data);
        int offset = 0;
        var MotoVersionItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoVersion>();
        while (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, true, 161U, 256U))
        {
            MotoVersionItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoVersion>(registry, version, data, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(MotoVersionItems.Count, 0, "MotoVersionItems");
        reader = new GeneratedWireReader(data[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, data.Length);
        return new global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoVersionList(
            MotoVersionItems);
    }

    public override int GetEncodedDataLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoVersionList parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 0;
        if (parameter.MotoVersionItems is null)
        {
            throw new global::System.ArgumentNullException("MotoVersionItems");
        }
        if (parameter.MotoVersionItems.Count < 0)
        {
            throw new global::System.ArgumentException("Member 'MotoVersionItems' requires cardinality 0..N.", "MotoVersionItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.MotoVersionItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "MotoVersionItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 1023, true, 161U, 256U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        return length;
    }

    public override int EncodeData(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoVersionList parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedDataLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.MotoVersionItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
