// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Codecs.V1_0_1;

internal sealed class MotoUTCTimestampCodec : global::LlrpNet.Protocol.Codecs.LlrpCustomParameterCodec<global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoUTCTimestamp>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public MotoUTCTimestampCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoUTCTimestamp Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> data)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(data);
        int offset = 0;
        ulong Microseconds = reader.ReadUInt64();
        offset += reader.BytePosition;
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, data.Length);
        return new global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoUTCTimestamp(
            Microseconds);
    }

    public override int GetEncodedDataLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoUTCTimestamp parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 8;
        return length;
    }

    public override int EncodeData(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoUTCTimestamp parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedDataLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteUInt64(parameter.Microseconds);
        offset += wireWriter.BytePosition;
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
