// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Codecs.V1_0_1;

internal sealed class MotoFilterListCodec : global::LlrpNet.Protocol.Codecs.LlrpCustomParameterCodec<global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoFilterList>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public MotoFilterListCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoFilterList Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> data)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(data);
        int offset = 0;
        bool UseFilter = reader.ReadBoolean();
        reader.ReadReservedBits(31);
        offset += reader.BytePosition;
        var MotoFilterRuleItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoFilterRule>();
        while (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, true, 161U, 254U))
        {
            MotoFilterRuleItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoFilterRule>(registry, version, data, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(MotoFilterRuleItems.Count, 0, "MotoFilterRuleItems");
        reader = new GeneratedWireReader(data[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, data.Length);
        return new global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoFilterList(
            UseFilter,
            MotoFilterRuleItems);
    }

    public override int GetEncodedDataLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoFilterList parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 4;
        if (parameter.MotoFilterRuleItems is null)
        {
            throw new global::System.ArgumentNullException("MotoFilterRuleItems");
        }
        if (parameter.MotoFilterRuleItems.Count < 0)
        {
            throw new global::System.ArgumentException("Member 'MotoFilterRuleItems' requires cardinality 0..N.", "MotoFilterRuleItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.MotoFilterRuleItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "MotoFilterRuleItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 1023, true, 161U, 254U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        return length;
    }

    public override int EncodeData(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoFilterList parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedDataLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteBoolean(parameter.UseFilter);
        wireWriter.WriteReservedBits(31);
        offset += wireWriter.BytePosition;
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.MotoFilterRuleItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
