// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Codecs.V1_0_1;

internal sealed class MotoAntennaConfigCodec : global::LlrpNet.Protocol.Codecs.LlrpCustomParameterCodec<global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoAntennaConfig>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public MotoAntennaConfigCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoAntennaConfig Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> data)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(data);
        int offset = 0;
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoAntennaStopCondition? MotoAntennaStopCondition = null;
        if (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, true, 161U, 704U))
        {
            MotoAntennaStopCondition = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoAntennaStopCondition>(registry, version, data, ref offset);
        }
        reader = new GeneratedWireReader(data[offset..]);
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoAntennaPhysicalPortConfig? MotoAntennaPhysicalPortConfig = null;
        if (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, true, 161U, 705U))
        {
            MotoAntennaPhysicalPortConfig = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoAntennaPhysicalPortConfig>(registry, version, data, ref offset);
        }
        reader = new GeneratedWireReader(data[offset..]);
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoAntennaQueryConfig? MotoAntennaQueryConfig = null;
        if (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, true, 161U, 710U))
        {
            MotoAntennaQueryConfig = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoAntennaQueryConfig>(registry, version, data, ref offset);
        }
        reader = new GeneratedWireReader(data[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, data.Length);
        return new global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoAntennaConfig(
            MotoAntennaStopCondition,
            MotoAntennaPhysicalPortConfig,
            MotoAntennaQueryConfig);
    }

    public override int GetEncodedDataLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoAntennaConfig parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 0;
        if (parameter.MotoAntennaStopCondition is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.MotoAntennaStopCondition, "MotoAntennaStopCondition", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.MotoAntennaStopCondition, 1023, true, 161U, 704U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.MotoAntennaStopCondition));
        }
        if (parameter.MotoAntennaPhysicalPortConfig is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.MotoAntennaPhysicalPortConfig, "MotoAntennaPhysicalPortConfig", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.MotoAntennaPhysicalPortConfig, 1023, true, 161U, 705U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.MotoAntennaPhysicalPortConfig));
        }
        if (parameter.MotoAntennaQueryConfig is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.MotoAntennaQueryConfig, "MotoAntennaQueryConfig", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.MotoAntennaQueryConfig, 1023, true, 161U, 710U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.MotoAntennaQueryConfig));
        }
        return length;
    }

    public override int EncodeData(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoAntennaConfig parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedDataLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        if (parameter.MotoAntennaStopCondition is not null)
        {
            offset += registry.EncodeParameter(version, parameter.MotoAntennaStopCondition, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (parameter.MotoAntennaPhysicalPortConfig is not null)
        {
            offset += registry.EncodeParameter(version, parameter.MotoAntennaPhysicalPortConfig, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (parameter.MotoAntennaQueryConfig is not null)
        {
            offset += registry.EncodeParameter(version, parameter.MotoAntennaQueryConfig, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
