// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Codecs.V1_0_1;

internal sealed class MotoC1G2RecommissionCodec : global::LlrpNet.Protocol.Codecs.LlrpCustomParameterCodec<global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoC1G2Recommission>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public MotoC1G2RecommissionCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoC1G2Recommission Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> data)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(data);
        int offset = 0;
        ushort OpSpecID = reader.ReadUInt16();
        uint KillPassword = reader.ReadUInt32();
        byte Operation = reader.ReadByte();
        reader.ReadReservedBits(8);
        offset += reader.BytePosition;
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, data.Length);
        return new global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoC1G2Recommission(
            OpSpecID,
            KillPassword,
            Operation);
    }

    public override int GetEncodedDataLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoC1G2Recommission parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 8;
        return length;
    }

    public override int EncodeData(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoC1G2Recommission parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedDataLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteUInt16(parameter.OpSpecID);
        wireWriter.WriteUInt32(parameter.KillPassword);
        wireWriter.WriteByte(parameter.Operation);
        wireWriter.WriteReservedBits(8);
        offset += wireWriter.BytePosition;
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
