// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Codecs.V1_0_1;

internal sealed class MotoC1G2BlockPermalockOpSpecResultCodec : global::LlrpNet.Protocol.Codecs.LlrpCustomParameterCodec<global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoC1G2BlockPermalockOpSpecResult>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public MotoC1G2BlockPermalockOpSpecResultCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoC1G2BlockPermalockOpSpecResult Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> data)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(data);
        int offset = 0;
        byte Result = reader.ReadByte();
        ushort OpSpecID = reader.ReadUInt16();
        global::System.Collections.Generic.IReadOnlyList<ushort> Status = reader.ReadUInt16Vector();
        offset += reader.BytePosition;
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, data.Length);
        return new global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoC1G2BlockPermalockOpSpecResult(
            Result,
            OpSpecID,
            Status);
    }

    public override int GetEncodedDataLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoC1G2BlockPermalockOpSpecResult parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 3;
        length = checked(length + GeneratedCodecRuntime.GetVectorLength(parameter.Status, 2));
        return length;
    }

    public override int EncodeData(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoC1G2BlockPermalockOpSpecResult parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedDataLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteByte(parameter.Result);
        wireWriter.WriteUInt16(parameter.OpSpecID);
        wireWriter.WriteUInt16Vector(parameter.Status);
        offset += wireWriter.BytePosition;
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
