// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Codecs.V1_0_1;

internal sealed class MotoImpinjQTCodec : global::LlrpNet.Protocol.Codecs.LlrpCustomParameterCodec<global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoImpinjQT>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public MotoImpinjQTCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoImpinjQT Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> data)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(data);
        int offset = 0;
        ushort OpSpecID = reader.ReadUInt16();
        uint AccessPassword = reader.ReadUInt32();
        bool QT_Write = reader.ReadBoolean();
        bool QT_Persist = reader.ReadBoolean();
        reader.ReadReservedBits(6);
        offset += reader.BytePosition;
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.QTData? QTData = null;
        if (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, true, 161U, 488U))
        {
            QTData = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.QTData>(registry, version, data, ref offset);
        }
        reader = new GeneratedWireReader(data[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, data.Length);
        return new global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoImpinjQT(
            OpSpecID,
            AccessPassword,
            QT_Write,
            QT_Persist,
            QTData);
    }

    public override int GetEncodedDataLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoImpinjQT parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 7;
        if (parameter.QTData is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.QTData, "QTData", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.QTData, 1023, true, 161U, 488U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.QTData));
        }
        return length;
    }

    public override int EncodeData(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Parameters.V1_0_1.MotoImpinjQT parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedDataLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteUInt16(parameter.OpSpecID);
        wireWriter.WriteUInt32(parameter.AccessPassword);
        wireWriter.WriteBoolean(parameter.QT_Write);
        wireWriter.WriteBoolean(parameter.QT_Persist);
        wireWriter.WriteReservedBits(6);
        offset += wireWriter.BytePosition;
        if (parameter.QTData is not null)
        {
            offset += registry.EncodeParameter(version, parameter.QTData, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
