// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Codecs.V1_0_1;

internal sealed class MOTO_PURGE_TAGS_RESPONSECodec : global::LlrpNet.Protocol.Codecs.LlrpCustomMessageCodec<global::LlrpNet.Protocol.Zebra.Messages.V1_0_1.MOTO_PURGE_TAGS_RESPONSE>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public MOTO_PURGE_TAGS_RESPONSECodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

public override global::LlrpNet.Protocol.Zebra.Messages.V1_0_1.MOTO_PURGE_TAGS_RESPONSE Decode(
    global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
    uint messageId,
    global::System.ReadOnlySpan<byte> data)
{
    GeneratedCodecRuntime.ValidateVersion(version, 1);
    var reader = new GeneratedWireReader(data);
    int offset = 0;
    global::LlrpNet.Protocol.Parameters.V1_0_1.LLRPStatus? LLRPStatus = null;
    if (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 287, false, 0U, 0U))
    {
        LLRPStatus = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.LLRPStatus>(registry, version, data, ref offset);
    }
    if (LLRPStatus is null)
    {
        throw GeneratedCodecRuntime.InvalidSequence("Required parameter 'LLRPStatus' is missing.");
    }
    reader = new GeneratedWireReader(data[offset..]);
    GeneratedCodecRuntime.ValidateDecodedEnd(offset, data.Length);
    return new global::LlrpNet.Protocol.Zebra.Messages.V1_0_1.MOTO_PURGE_TAGS_RESPONSE(
        messageId,
        LLRPStatus!);
}

    public override int GetEncodedDataLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Messages.V1_0_1.MOTO_PURGE_TAGS_RESPONSE message)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(message);
        int length = 0;
        if (message.LLRPStatus is null)
        {
            throw new global::System.ArgumentNullException("LLRPStatus");
        }
        GeneratedCodecRuntime.ValidateParameterMatch(message.LLRPStatus!, "LLRPStatus", GeneratedCodecRuntime.IsParameterMatch(registry, version, message.LLRPStatus!, 287, false, 0U, 0U));
        length = checked(length + registry.GetEncodedParameterLength(version, message.LLRPStatus!));
        return length;
    }

    public override int EncodeData(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Zebra.Messages.V1_0_1.MOTO_PURGE_TAGS_RESPONSE message,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedDataLength(version, message);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        offset += registry.EncodeParameter(version, message.LLRPStatus!, destination[offset..]);
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
