// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Messages.V1_1;

/// <summary>Generated LLRP message 'STOP_ROSPEC'.</summary>
/// <param name="MessageId">The common LLRP message identifier.</param>
/// <param name="ROSpecID">Wire field 'ROSpecID' (U32).</param>
public sealed record STOP_ROSPEC(
    uint MessageId,
    uint ROSpecID
) : global::LlrpNet.Protocol.Messages.ILlrpMessage
{
    public const ushort TypeNumber = 23;
    public const ushort MessageType = TypeNumber;
}
