// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Messages.V1_1;

/// <summary>Generated LLRP message 'GET_ACCESSSPECS_RESPONSE'.</summary>
/// <param name="MessageId">The common LLRP message identifier.</param>
/// <param name="LLRPStatus">LLRP parameter 'LLRPStatus' with cardinality 1..1.</param>
/// <param name="AccessSpecItems">LLRP parameter 'AccessSpec' with cardinality 0..N.</param>
public sealed record GET_ACCESSSPECS_RESPONSE(
    uint MessageId,
    global::LlrpNet.Protocol.Parameters.V1_1.LLRPStatus LLRPStatus,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.V1_1.AccessSpec> AccessSpecItems
) : global::LlrpNet.Protocol.Messages.ILlrpMessage
{
    public const ushort TypeNumber = 54;
    public const ushort MessageType = TypeNumber;
}
