// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Messages.V1_1;

/// <summary>Generated LLRP message 'GET_SUPPORTED_VERSION_RESPONSE'.</summary>
/// <param name="MessageId">The common LLRP message identifier.</param>
/// <param name="LLRPStatus">LLRP parameter 'LLRPStatus' with cardinality 1..1.</param>
/// <param name="CurrentVersion">Wire field 'CurrentVersion' (U8).</param>
/// <param name="SupportedVersion">Wire field 'SupportedVersion' (U8).</param>
public sealed record GET_SUPPORTED_VERSION_RESPONSE(
    uint MessageId,
    global::LlrpNet.Protocol.Parameters.V1_1.LLRPStatus LLRPStatus,
    byte CurrentVersion,
    byte SupportedVersion
) : global::LlrpNet.Protocol.Messages.ILlrpMessage
{
    public const ushort TypeNumber = 56;
    public const ushort MessageType = TypeNumber;
}
