// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Messages.V1_1;

/// <summary>Generated LLRP message 'SET_PROTOCOL_VERSION_RESPONSE'.</summary>
/// <param name="MessageId">The common LLRP message identifier.</param>
/// <param name="LLRPStatus">LLRP parameter 'LLRPStatus' with cardinality 1..1.</param>
public sealed record SET_PROTOCOL_VERSION_RESPONSE(
    uint MessageId,
    global::LlrpNet.Protocol.Parameters.V1_1.LLRPStatus LLRPStatus
) : global::LlrpNet.Protocol.Messages.ILlrpMessage
{
    public const ushort TypeNumber = 57;
    public const ushort MessageType = TypeNumber;
}
