// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Impinj.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ImpinjEnableCRHandle'.</summary>
/// <param name="CRHandleMode">Wire field 'CRHandleMode' (U8).</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ImpinjEnableCRHandle(
    global::LlrpNet.Protocol.Impinj.Enumerations.V1_0_1.ImpinjCRHandleMode CRHandleMode,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 25882U;
    public const uint Subtype = 1589U;
}
