using LlrpNet.Core.Protocol;

namespace LlrpSdk;

/// <summary>Identifies how the SDK produced a high-level settings baseline.</summary>
public enum ReaderSettingsDefaultSource
{
    /// <summary>Portable LLRP defaults that do not require a recognized reader profile.</summary>
    Generic,

    /// <summary>A connected reader's vendor, model, firmware, and capability profile.</summary>
    ReaderProfile,
}

/// <summary>
/// A complete, editable SDK-recommended <see cref="ReaderSettings"/> baseline for one connected reader.
/// </summary>
/// <remarks>
/// This is deliberately distinct from <see cref="ReaderSettingsSnapshot"/>. A snapshot represents facts read
/// from the device; this type represents a profile-generated starting point that an application may edit and apply.
/// </remarks>
public sealed record ReaderSettingsDefaults
{
    /// <summary>Gets the editable high-level settings generated by the SDK.</summary>
    public ReaderSettings Settings { get; init; } = new() { Inventory = new InventorySettings() };

    /// <summary>Gets the stable identifier of the selected default profile.</summary>
    public string ProfileId { get; init; } = "llrp.generic";

    /// <summary>Gets whether the result is generic or resolved for a concrete reader profile.</summary>
    public ReaderSettingsDefaultSource Source { get; init; } = ReaderSettingsDefaultSource.Generic;

    /// <summary>Gets human-readable decisions and caveats made while resolving the baseline.</summary>
    public IReadOnlyList<string> Notes { get; init; } = Array.Empty<string>();

    /// <summary>Creates the portable standard LLRP baseline usable before a reader is connected.</summary>
    public static ReaderSettingsDefaults CreateGeneric() => new();
}

/// <summary>Supplies initialized reader facts to a model-specific settings-default contributor.</summary>
public sealed record ReaderSettingsDefaultContext(
    ReaderIdentity Identity,
    ReaderCapabilities Capabilities,
    LlrpProtocolVersion ProtocolVersion);

/// <summary>Generates an editable high-level settings baseline for a recognized connected reader.</summary>
public interface IReaderSettingsDefaultsContributor
{
    /// <summary>Gets the stable contributor identifier used for duplicate detection.</summary>
    public string Id { get; }

    /// <summary>Returns the profile-generated defaults, or <see langword="null"/> when this profile has no recommendation.</summary>
    public ReaderSettingsDefaults? GetDefaultSettings(ReaderSettingsDefaultContext context);
}
