// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TLV parameter 'Custom'.</summary>
/// <param name="VendorIdentifier">Wire field 'VendorIdentifier' (U32).</param>
/// <param name="ParameterSubtype">Wire field 'ParameterSubtype' (U32).</param>
/// <param name="Data">Wire field 'Data' (BytesToEnd).</param>
public sealed record Custom(
    uint VendorIdentifier,
    uint ParameterSubtype,
    global::System.ReadOnlyMemory<byte> Data
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const ushort ParameterType = 1023;
}
