// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TLV parameter 'FrequencyHopTable'.</summary>
/// <param name="HopTableID">Wire field 'HopTableID' (U8).</param>
/// <param name="Frequency">Wire field 'Frequency' (U32Vector).</param>
public sealed record FrequencyHopTable(
    byte HopTableID,
    global::System.Collections.Generic.IReadOnlyList<uint> Frequency
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 147;
    public const ushort ParameterType = 147;
}
