// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TLV parameter 'RFSurveySpec'.</summary>
/// <param name="AntennaID">Wire field 'AntennaID' (U16).</param>
/// <param name="StartFrequency">Wire field 'StartFrequency' (U32).</param>
/// <param name="EndFrequency">Wire field 'EndFrequency' (U32).</param>
/// <param name="RFSurveySpecStopTrigger">LLRP parameter 'RFSurveySpecStopTrigger' with cardinality 1..1.</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record RFSurveySpec(
    ushort AntennaID,
    uint StartFrequency,
    uint EndFrequency,
    global::LlrpNet.Protocol.Parameters.V1_0_1.RFSurveySpecStopTrigger RFSurveySpecStopTrigger,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V1_0_1.ISpecParameter
{
    public const ushort TypeNumber = 187;
    public const ushort ParameterType = 187;
}
