// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TLV parameter 'AccessCommand'.</summary>
/// <param name="AirProtocolTagSpec">LLRP choice 'AirProtocolTagSpec' with cardinality 1..1.</param>
/// <param name="AccessCommandOpSpecItems">LLRP choice 'AccessCommandOpSpec' with cardinality 1..N.</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record AccessCommand(
    global::LlrpNet.Protocol.Choices.V1_0_1.IAirProtocolTagSpec AirProtocolTagSpec,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> AccessCommandOpSpecItems,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 209;
    public const ushort ParameterType = 209;
}
