// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TLV parameter 'LLRPConfigurationStateValue'.</summary>
/// <param name="LLRPConfigurationStateValue_2">Wire field 'LLRPConfigurationStateValue' (U32).</param>
public sealed record LLRPConfigurationStateValue(
    uint LLRPConfigurationStateValue_2
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 217;
    public const ushort ParameterType = 217;
}
