// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TLV parameter 'EventsAndReports'.</summary>
/// <param name="HoldEventsAndReportsUponReconnect">Wire field 'HoldEventsAndReportsUponReconnect' (U1).</param>
public sealed record EventsAndReports(
    bool HoldEventsAndReportsUponReconnect
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 226;
    public const ushort ParameterType = 226;
}
