// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TLV parameter 'AccessReportSpec'.</summary>
/// <param name="AccessReportTrigger">Wire field 'AccessReportTrigger' (U8).</param>
public sealed record AccessReportSpec(
    global::LlrpNet.Protocol.Enumerations.V1_0_1.AccessReportTriggerType AccessReportTrigger
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 239;
    public const ushort ParameterType = 239;
}
