// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TLV parameter 'TagReportData'.</summary>
/// <param name="EPCParameter">LLRP choice 'EPCParameter' with cardinality 1..1.</param>
/// <param name="ROSpecID">LLRP parameter 'ROSpecID' with cardinality 0..1.</param>
/// <param name="SpecIndex">LLRP parameter 'SpecIndex' with cardinality 0..1.</param>
/// <param name="InventoryParameterSpecID">LLRP parameter 'InventoryParameterSpecID' with cardinality 0..1.</param>
/// <param name="AntennaID">LLRP parameter 'AntennaID' with cardinality 0..1.</param>
/// <param name="PeakRSSI">LLRP parameter 'PeakRSSI' with cardinality 0..1.</param>
/// <param name="ChannelIndex">LLRP parameter 'ChannelIndex' with cardinality 0..1.</param>
/// <param name="FirstSeenTimestampUTC">LLRP parameter 'FirstSeenTimestampUTC' with cardinality 0..1.</param>
/// <param name="FirstSeenTimestampUptime">LLRP parameter 'FirstSeenTimestampUptime' with cardinality 0..1.</param>
/// <param name="LastSeenTimestampUTC">LLRP parameter 'LastSeenTimestampUTC' with cardinality 0..1.</param>
/// <param name="LastSeenTimestampUptime">LLRP parameter 'LastSeenTimestampUptime' with cardinality 0..1.</param>
/// <param name="TagSeenCount">LLRP parameter 'TagSeenCount' with cardinality 0..1.</param>
/// <param name="AirProtocolTagDataItems">LLRP choice 'AirProtocolTagData' with cardinality 0..N.</param>
/// <param name="AccessSpecID">LLRP parameter 'AccessSpecID' with cardinality 0..1.</param>
/// <param name="AccessCommandOpSpecResultItems">LLRP choice 'AccessCommandOpSpecResult' with cardinality 0..N.</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record TagReportData(
    global::LlrpNet.Protocol.Choices.V1_0_1.IEPCParameter EPCParameter,
    global::LlrpNet.Protocol.Parameters.V1_0_1.ROSpecID? ROSpecID,
    global::LlrpNet.Protocol.Parameters.V1_0_1.SpecIndex? SpecIndex,
    global::LlrpNet.Protocol.Parameters.V1_0_1.InventoryParameterSpecID? InventoryParameterSpecID,
    global::LlrpNet.Protocol.Parameters.V1_0_1.AntennaID? AntennaID,
    global::LlrpNet.Protocol.Parameters.V1_0_1.PeakRSSI? PeakRSSI,
    global::LlrpNet.Protocol.Parameters.V1_0_1.ChannelIndex? ChannelIndex,
    global::LlrpNet.Protocol.Parameters.V1_0_1.FirstSeenTimestampUTC? FirstSeenTimestampUTC,
    global::LlrpNet.Protocol.Parameters.V1_0_1.FirstSeenTimestampUptime? FirstSeenTimestampUptime,
    global::LlrpNet.Protocol.Parameters.V1_0_1.LastSeenTimestampUTC? LastSeenTimestampUTC,
    global::LlrpNet.Protocol.Parameters.V1_0_1.LastSeenTimestampUptime? LastSeenTimestampUptime,
    global::LlrpNet.Protocol.Parameters.V1_0_1.TagSeenCount? TagSeenCount,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Choices.V1_0_1.IAirProtocolTagData> AirProtocolTagDataItems,
    global::LlrpNet.Protocol.Parameters.V1_0_1.AccessSpecID? AccessSpecID,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> AccessCommandOpSpecResultItems,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 240;
    public const ushort ParameterType = 240;
}
