// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TV parameter 'ROSpecID'.</summary>
/// <param name="ROSpecID_2">Wire field 'ROSpecID' (U32).</param>
public sealed record ROSpecID(
    uint ROSpecID_2
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 9;
    public const ushort ParameterType = 9;
}
