// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TV parameter 'AntennaID'.</summary>
/// <param name="AntennaID_2">Wire field 'AntennaID' (U16).</param>
public sealed record AntennaID(
    ushort AntennaID_2
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1;
    public const ushort ParameterType = 1;
}
