// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TLV parameter 'ReaderEventNotificationData'.</summary>
/// <param name="Timestamp">LLRP choice 'Timestamp' with cardinality 1..1.</param>
/// <param name="HoppingEvent">LLRP parameter 'HoppingEvent' with cardinality 0..1.</param>
/// <param name="GPIEvent">LLRP parameter 'GPIEvent' with cardinality 0..1.</param>
/// <param name="ROSpecEvent">LLRP parameter 'ROSpecEvent' with cardinality 0..1.</param>
/// <param name="ReportBufferLevelWarningEvent">LLRP parameter 'ReportBufferLevelWarningEvent' with cardinality 0..1.</param>
/// <param name="ReportBufferOverflowErrorEvent">LLRP parameter 'ReportBufferOverflowErrorEvent' with cardinality 0..1.</param>
/// <param name="ReaderExceptionEvent">LLRP parameter 'ReaderExceptionEvent' with cardinality 0..1.</param>
/// <param name="RFSurveyEvent">LLRP parameter 'RFSurveyEvent' with cardinality 0..1.</param>
/// <param name="AISpecEvent">LLRP parameter 'AISpecEvent' with cardinality 0..1.</param>
/// <param name="AntennaEvent">LLRP parameter 'AntennaEvent' with cardinality 0..1.</param>
/// <param name="ConnectionAttemptEvent">LLRP parameter 'ConnectionAttemptEvent' with cardinality 0..1.</param>
/// <param name="ConnectionCloseEvent">LLRP parameter 'ConnectionCloseEvent' with cardinality 0..1.</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ReaderEventNotificationData(
    global::LlrpNet.Protocol.Choices.V1_0_1.ITimestamp Timestamp,
    global::LlrpNet.Protocol.Parameters.V1_0_1.HoppingEvent? HoppingEvent,
    global::LlrpNet.Protocol.Parameters.V1_0_1.GPIEvent? GPIEvent,
    global::LlrpNet.Protocol.Parameters.V1_0_1.ROSpecEvent? ROSpecEvent,
    global::LlrpNet.Protocol.Parameters.V1_0_1.ReportBufferLevelWarningEvent? ReportBufferLevelWarningEvent,
    global::LlrpNet.Protocol.Parameters.V1_0_1.ReportBufferOverflowErrorEvent? ReportBufferOverflowErrorEvent,
    global::LlrpNet.Protocol.Parameters.V1_0_1.ReaderExceptionEvent? ReaderExceptionEvent,
    global::LlrpNet.Protocol.Parameters.V1_0_1.RFSurveyEvent? RFSurveyEvent,
    global::LlrpNet.Protocol.Parameters.V1_0_1.AISpecEvent? AISpecEvent,
    global::LlrpNet.Protocol.Parameters.V1_0_1.AntennaEvent? AntennaEvent,
    global::LlrpNet.Protocol.Parameters.V1_0_1.ConnectionAttemptEvent? ConnectionAttemptEvent,
    global::LlrpNet.Protocol.Parameters.V1_0_1.ConnectionCloseEvent? ConnectionCloseEvent,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 246;
    public const ushort ParameterType = 246;
}
