// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TLV parameter 'ReportBufferOverflowErrorEvent'.</summary>
public sealed record ReportBufferOverflowErrorEvent : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 251;
    public const ushort ParameterType = 251;
}
