// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TV parameter 'OpSpecID'.</summary>
/// <param name="OpSpecID_2">Wire field 'OpSpecID' (U16).</param>
public sealed record OpSpecID(
    ushort OpSpecID_2
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 17;
    public const ushort ParameterType = 17;
}
