// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TLV parameter 'ConnectionCloseEvent'.</summary>
public sealed record ConnectionCloseEvent : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 257;
    public const ushort ParameterType = 257;
}
