// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TLV parameter 'FieldError'.</summary>
/// <param name="FieldNum">Wire field 'FieldNum' (U16).</param>
/// <param name="ErrorCode">Wire field 'ErrorCode' (U16).</param>
public sealed record FieldError(
    ushort FieldNum,
    global::LlrpNet.Protocol.Enumerations.V1_0_1.StatusCode ErrorCode
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 288;
    public const ushort ParameterType = 288;
}
