// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TLV parameter 'ParameterError'.</summary>
/// <param name="ParameterType_2">Wire field 'ParameterType' (U16).</param>
/// <param name="ErrorCode">Wire field 'ErrorCode' (U16).</param>
/// <param name="FieldError">LLRP parameter 'FieldError' with cardinality 0..1.</param>
/// <param name="ParameterError_2">LLRP parameter 'ParameterError' with cardinality 0..1.</param>
public sealed record ParameterError(
    ushort ParameterType_2,
    global::LlrpNet.Protocol.Enumerations.V1_0_1.StatusCode ErrorCode,
    global::LlrpNet.Protocol.Parameters.V1_0_1.FieldError? FieldError,
    global::LlrpNet.Protocol.Parameters.V1_0_1.ParameterError? ParameterError_2
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 289;
}
