// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TLV parameter 'C1G2UHFRFModeTableEntry'.</summary>
/// <param name="ModeIdentifier">Wire field 'ModeIdentifier' (U32).</param>
/// <param name="DRValue">Wire field 'DRValue' (U1).</param>
/// <param name="EPCHAGTCConformance">Wire field 'EPCHAGTCConformance' (U1).</param>
/// <param name="MValue">Wire field 'MValue' (U8).</param>
/// <param name="ForwardLinkModulation">Wire field 'ForwardLinkModulation' (U8).</param>
/// <param name="SpectralMaskIndicator">Wire field 'SpectralMaskIndicator' (U8).</param>
/// <param name="BDRValue">Wire field 'BDRValue' (U32).</param>
/// <param name="PIEValue">Wire field 'PIEValue' (U32).</param>
/// <param name="MinTariValue">Wire field 'MinTariValue' (U32).</param>
/// <param name="MaxTariValue">Wire field 'MaxTariValue' (U32).</param>
/// <param name="StepTariValue">Wire field 'StepTariValue' (U32).</param>
public sealed record C1G2UHFRFModeTableEntry(
    uint ModeIdentifier,
    global::LlrpNet.Protocol.Enumerations.V1_0_1.C1G2DRValue DRValue,
    bool EPCHAGTCConformance,
    global::LlrpNet.Protocol.Enumerations.V1_0_1.C1G2MValue MValue,
    global::LlrpNet.Protocol.Enumerations.V1_0_1.C1G2ForwardLinkModulation ForwardLinkModulation,
    global::LlrpNet.Protocol.Enumerations.V1_0_1.C1G2SpectralMaskIndicator SpectralMaskIndicator,
    uint BDRValue,
    uint PIEValue,
    uint MinTariValue,
    uint MaxTariValue,
    uint StepTariValue
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 329;
    public const ushort ParameterType = 329;
}
