// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TLV parameter 'C1G2Write'.</summary>
/// <param name="OpSpecID">Wire field 'OpSpecID' (U16).</param>
/// <param name="AccessPassword">Wire field 'AccessPassword' (U32).</param>
/// <param name="MB">Wire field 'MB' (U2).</param>
/// <param name="WordPointer">Wire field 'WordPointer' (U16).</param>
/// <param name="WriteData">Wire field 'WriteData' (U16Vector).</param>
public sealed record C1G2Write(
    ushort OpSpecID,
    uint AccessPassword,
    byte MB,
    ushort WordPointer,
    global::System.Collections.Generic.IReadOnlyList<ushort> WriteData
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V1_0_1.IAccessCommandOpSpec, global::LlrpNet.Protocol.Choices.V1_0_1.IC1G2OpSpec, global::LlrpNet.Protocol.Choices.V1_0_1.IAirProtocolOpSpec
{
    public const ushort TypeNumber = 342;
    public const ushort ParameterType = 342;
}
