// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TLV parameter 'C1G2Lock'.</summary>
/// <param name="OpSpecID">Wire field 'OpSpecID' (U16).</param>
/// <param name="AccessPassword">Wire field 'AccessPassword' (U32).</param>
/// <param name="C1G2LockPayloadItems">LLRP parameter 'C1G2LockPayload' with cardinality 1..N.</param>
public sealed record C1G2Lock(
    ushort OpSpecID,
    uint AccessPassword,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.V1_0_1.C1G2LockPayload> C1G2LockPayloadItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V1_0_1.IAccessCommandOpSpec, global::LlrpNet.Protocol.Choices.V1_0_1.IC1G2OpSpec, global::LlrpNet.Protocol.Choices.V1_0_1.IAirProtocolOpSpec
{
    public const ushort TypeNumber = 344;
    public const ushort ParameterType = 344;
}
