// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TV parameter 'C1G2_CRC'.</summary>
/// <param name="CRC">Wire field 'CRC' (U16).</param>
public sealed record C1G2_CRC(
    ushort CRC
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V1_0_1.IAirProtocolTagData
{
    public const ushort TypeNumber = 11;
    public const ushort ParameterType = 11;
}
