// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_0_1;

/// <summary>Generated LLRP TLV parameter 'C1G2WriteOpSpecResult'.</summary>
/// <param name="Result">Wire field 'Result' (U8).</param>
/// <param name="OpSpecID">Wire field 'OpSpecID' (U16).</param>
/// <param name="NumWordsWritten">Wire field 'NumWordsWritten' (U16).</param>
public sealed record C1G2WriteOpSpecResult(
    global::LlrpNet.Protocol.Enumerations.V1_0_1.C1G2WriteResultType Result,
    ushort OpSpecID,
    ushort NumWordsWritten
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V1_0_1.IAccessCommandOpSpecResult
{
    public const ushort TypeNumber = 350;
    public const ushort ParameterType = 350;
}
