// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1;

/// <summary>Generated LLRP custom enumeration 'ImpinjLowDutyCycleMode'.</summary>
public enum ImpinjLowDutyCycleMode : long
{
    Disabled = 0L,
    Enabled = 1L,
}
