// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1;

/// <summary>Generated LLRP custom enumeration 'ImpinjQTDataProfile'.</summary>
public enum ImpinjQTDataProfile : long
{
    Unknown = 0L,
    Private = 1L,
    Public = 2L,
}
