// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1;

/// <summary>Generated LLRP custom enumeration 'ImpinjGPSCoordinatesMode'.</summary>
public enum ImpinjGPSCoordinatesMode : long
{
    Disabled = 0L,
    Enabled = 1L,
}
