// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1;

/// <summary>Generated LLRP custom enumeration 'ImpinjDirectionRFMode'.</summary>
public enum ImpinjDirectionRFMode : long
{
    HighSensitivity = 0L,
    HighPerformance = 1L,
}
