// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1;

/// <summary>Generated LLRP custom enumeration 'ImpinjDirectionTagPopulationStatus'.</summary>
public enum ImpinjDirectionTagPopulationStatus : long
{
    OK = 0L,
    UserOverflow = 1L,
    SystemOverflow = 2L,
}
