// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1;

/// <summary>Generated LLRP custom enumeration 'ImpinjMarginReadResultType'.</summary>
public enum ImpinjMarginReadResultType : long
{
    Success = 0L,
    Failure = 1L,
    Insufficient_Power = 2L,
    Nonspecific_Tag_Error = 3L,
    No_Response_From_Tag = 4L,
    Nonspecific_Reader_Error = 5L,
    Incorrect_Password_Error = 6L,
    Tag_Memory_Overrun_Error = 7L,
    Tag_Memory_Locked_Error = 8L,
}
