// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1;

/// <summary>Generated LLRP custom enumeration 'ImpinjEnhancedIntegraResultType'.</summary>
public enum ImpinjEnhancedIntegraResultType : long
{
    No_Parity_Error = 0L,
    PC_Parity_Error = 1L,
    EPC_Parity_Error = 2L,
    PC_or_TID_Parity_Error = 3L,
    EPC_or_TID_Parity_Error = 4L,
    Memory_Read_Parity_Error = 5L,
}
