// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ImpinjReducedPowerFrequencyList'.</summary>
/// <param name="ReducedPowerMode">Wire field 'ReducedPowerMode' (U16).</param>
/// <param name="ChannelList">Wire field 'ChannelList' (U16Vector).</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ImpinjReducedPowerFrequencyList(
    global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjReducedPowerMode ReducedPowerMode,
    global::System.Collections.Generic.IReadOnlyList<ushort> ChannelList,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 25882U;
    public const uint Subtype = 27U;
}
