// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ImpinjHubVersions'.</summary>
/// <param name="ImpinjArrayVersionItems">LLRP parameter 'ImpinjArrayVersion' with cardinality 1..N.</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ImpinjHubVersions(
    global::System.Collections.Generic.IReadOnlyList<global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjArrayVersion> ImpinjArrayVersionItems,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 25882U;
    public const uint Subtype = 1537U;
}
