// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ImpinjGPIDebounceConfiguration'.</summary>
/// <param name="GPIPortNum">Wire field 'GPIPortNum' (U16).</param>
/// <param name="GPIDebounceTimerMSec">Wire field 'GPIDebounceTimerMSec' (U32).</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ImpinjGPIDebounceConfiguration(
    ushort GPIPortNum,
    uint GPIDebounceTimerMSec,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 25882U;
    public const uint Subtype = 36U;
}
