// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ImpinjAccessSpecConfiguration'.</summary>
/// <param name="ImpinjBlockWriteWordCount">LLRP parameter 'ImpinjBlockWriteWordCount' with cardinality 0..1.</param>
/// <param name="ImpinjOpSpecRetryCount">LLRP parameter 'ImpinjOpSpecRetryCount' with cardinality 0..1.</param>
/// <param name="ImpinjAccessSpecOrdering">LLRP parameter 'ImpinjAccessSpecOrdering' with cardinality 0..1.</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ImpinjAccessSpecConfiguration(
    global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjBlockWriteWordCount? ImpinjBlockWriteWordCount,
    global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjOpSpecRetryCount? ImpinjOpSpecRetryCount,
    global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjAccessSpecOrdering? ImpinjAccessSpecOrdering,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 25882U;
    public const uint Subtype = 40U;
}
