// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ImpinjGetBlockPermalockStatusOpSpecResult'.</summary>
/// <param name="Result">Wire field 'Result' (U8).</param>
/// <param name="OpSpecID">Wire field 'OpSpecID' (U16).</param>
/// <param name="PermalockStatus">Wire field 'PermalockStatus' (U16Vector).</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ImpinjGetBlockPermalockStatusOpSpecResult(
    global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjGetBlockPermalockStatusResultType Result,
    ushort OpSpecID,
    global::System.Collections.Generic.IReadOnlyList<ushort> PermalockStatus,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V1_0_1.IAccessCommandOpSpecResult
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 25882U;
    public const uint Subtype = 45U;
}
