// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ImpinjSetQTConfig'.</summary>
/// <param name="OpSpecID">Wire field 'OpSpecID' (U16).</param>
/// <param name="AccessPassword">Wire field 'AccessPassword' (U32).</param>
/// <param name="DataProfile">Wire field 'DataProfile' (U8).</param>
/// <param name="AccessRange">Wire field 'AccessRange' (U8).</param>
/// <param name="Persistence">Wire field 'Persistence' (U8).</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ImpinjSetQTConfig(
    ushort OpSpecID,
    uint AccessPassword,
    global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjQTDataProfile DataProfile,
    global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjQTAccessRange AccessRange,
    global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjQTPersistence Persistence,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V1_0_1.IAccessCommandOpSpec
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 25882U;
    public const uint Subtype = 46U;
}
