// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ImpinjInventoryConfiguration'.</summary>
/// <param name="EnableAntDwellTimeLimit">Wire field 'EnableAntDwellTimeLimit' (U1).</param>
/// <param name="EnableSelectGapClose">Wire field 'EnableSelectGapClose' (U1).</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ImpinjInventoryConfiguration(
    bool EnableAntDwellTimeLimit,
    bool EnableSelectGapClose,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 25882U;
    public const uint Subtype = 69U;
}
