// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ImpinjTiltConfiguration'.</summary>
/// <param name="XAxis">Wire field 'XAxis' (S32).</param>
/// <param name="YAxis">Wire field 'YAxis' (S32).</param>
/// <param name="ZAxis">Wire field 'ZAxis' (S32).</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ImpinjTiltConfiguration(
    int XAxis,
    int YAxis,
    int ZAxis,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 25882U;
    public const uint Subtype = 1522U;
}
