// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ImpinjBeaconConfiguration'.</summary>
/// <param name="BeaconState">Wire field 'BeaconState' (U1).</param>
/// <param name="BeaconDurationSeconds">Wire field 'BeaconDurationSeconds' (U64).</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ImpinjBeaconConfiguration(
    bool BeaconState,
    ulong BeaconDurationSeconds,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 25882U;
    public const uint Subtype = 1523U;
}
