// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ImpinjDiagnosticReport'.</summary>
/// <param name="Metric">Wire field 'Metric' (U32Vector).</param>
public sealed record ImpinjDiagnosticReport(
    global::System.Collections.Generic.IReadOnlyList<uint> Metric
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 25882U;
    public const uint Subtype = 1539U;
}
