// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ImpinjPlacementConfiguration'.</summary>
/// <param name="HeightCm">Wire field 'HeightCm' (U16).</param>
/// <param name="FacilityXLocationCm">Wire field 'FacilityXLocationCm' (S32).</param>
/// <param name="FacilityYLocationCm">Wire field 'FacilityYLocationCm' (S32).</param>
/// <param name="OrientationDegrees">Wire field 'OrientationDegrees' (S16).</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ImpinjPlacementConfiguration(
    ushort HeightCm,
    int FacilityXLocationCm,
    int FacilityYLocationCm,
    short OrientationDegrees,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 25882U;
    public const uint Subtype = 1540U;
}
