// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ImpinjLocationConfig'.</summary>
/// <param name="ComputeWindowSeconds">Wire field 'ComputeWindowSeconds' (U16).</param>
/// <param name="TagAgeIntervalSeconds">Wire field 'TagAgeIntervalSeconds' (U16).</param>
/// <param name="UpdateIntervalSeconds">Wire field 'UpdateIntervalSeconds' (U16).</param>
/// <param name="ImpinjDisabledAntennas">LLRP parameter 'ImpinjDisabledAntennas' with cardinality 0..1.</param>
/// <param name="ImpinjLocationAlgorithmControl">LLRP parameter 'ImpinjLocationAlgorithmControl' with cardinality 0..1.</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ImpinjLocationConfig(
    ushort ComputeWindowSeconds,
    ushort TagAgeIntervalSeconds,
    ushort UpdateIntervalSeconds,
    global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjDisabledAntennas? ImpinjDisabledAntennas,
    global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLocationAlgorithmControl? ImpinjLocationAlgorithmControl,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 25882U;
    public const uint Subtype = 1542U;
}
