// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ImpinjDISpec'.</summary>
/// <param name="ImpinjDirectionSectors">LLRP parameter 'ImpinjDirectionSectors' with cardinality 1..1.</param>
/// <param name="ImpinjDirectionConfig">LLRP parameter 'ImpinjDirectionConfig' with cardinality 0..1.</param>
/// <param name="ImpinjC1G2DirectionConfig">LLRP parameter 'ImpinjC1G2DirectionConfig' with cardinality 0..1.</param>
/// <param name="ImpinjDirectionReporting">LLRP parameter 'ImpinjDirectionReporting' with cardinality 0..1.</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ImpinjDISpec(
    global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjDirectionSectors ImpinjDirectionSectors,
    global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjDirectionConfig? ImpinjDirectionConfig,
    global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjC1G2DirectionConfig? ImpinjC1G2DirectionConfig,
    global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjDirectionReporting? ImpinjDirectionReporting,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V1_0_1.ISpecParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 25882U;
    public const uint Subtype = 1567U;
}
