// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ImpinjDirectionReportData'.</summary>
/// <param name="Type">Wire field 'Type' (U8).</param>
/// <param name="TagPopulationStatus">Wire field 'TagPopulationStatus' (U8).</param>
/// <param name="FirstSeenSectorID">Wire field 'FirstSeenSectorID' (U8).</param>
/// <param name="FirstSeenTimestampUTC">Wire field 'FirstSeenTimestampUTC' (U64).</param>
/// <param name="LastSeenSectorID">Wire field 'LastSeenSectorID' (U8).</param>
/// <param name="LastSeenTimestampUTC">Wire field 'LastSeenTimestampUTC' (U64).</param>
/// <param name="ImpinjDirectionDiagnosticData">LLRP parameter 'ImpinjDirectionDiagnosticData' with cardinality 0..1.</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ImpinjDirectionReportData(
    global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjDirectionReportType Type,
    global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjDirectionTagPopulationStatus TagPopulationStatus,
    byte FirstSeenSectorID,
    ulong FirstSeenTimestampUTC,
    byte LastSeenSectorID,
    ulong LastSeenTimestampUTC,
    global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjDirectionDiagnosticData? ImpinjDirectionDiagnosticData,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 25882U;
    public const uint Subtype = 1573U;
}
