// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ImpinjxArrayDirectionCapabilities'.</summary>
/// <param name="SystemTagPopulationLimitHighSensitivity">Wire field 'SystemTagPopulationLimitHighSensitivity' (U16).</param>
/// <param name="SystemTagPopulationLimitHighPerformance">Wire field 'SystemTagPopulationLimitHighPerformance' (U16).</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ImpinjxArrayDirectionCapabilities(
    ushort SystemTagPopulationLimitHighSensitivity,
    ushort SystemTagPopulationLimitHighPerformance,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 25882U;
    public const uint Subtype = 1575U;
}
