// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ImpinjAuthenticate'.</summary>
/// <param name="OpSpecID">Wire field 'OpSpecID' (U16).</param>
/// <param name="AccessPassword">Wire field 'AccessPassword' (U32).</param>
/// <param name="SendRep">Wire field 'SendRep' (U1).</param>
/// <param name="IncRepLen">Wire field 'IncRepLen' (U1).</param>
/// <param name="CSI">Wire field 'CSI' (U8).</param>
/// <param name="Message">Wire field 'Message' (U1Vector).</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ImpinjAuthenticate(
    ushort OpSpecID,
    uint AccessPassword,
    bool SendRep,
    bool IncRepLen,
    byte CSI,
    global::System.Collections.Generic.IReadOnlyList<bool> Message,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V1_0_1.IAccessCommandOpSpec
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 25882U;
    public const uint Subtype = 1584U;
}
