// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Parameters.V1_0_1;

/// <summary>Generated custom LLRP parameter 'ImpinjEndpointICVerificationConfig'.</summary>
/// <param name="EndpointICVerificationMode">Wire field 'EndpointICVerificationMode' (U8).</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ImpinjEndpointICVerificationConfig(
    global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjEndpointICVerificationMode EndpointICVerificationMode,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 1023;
    public const uint VendorIdentifier = 25882U;
    public const uint Subtype = 1593U;
}
