// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Codecs.V1_0_1;

internal ref struct GeneratedWireReader
{
    private readonly global::System.ReadOnlySpan<byte> source;
    private int bitPosition;

    public GeneratedWireReader(global::System.ReadOnlySpan<byte> source)
    {
        this.source = source;
        bitPosition = 0;
    }

    public int BytePosition
    {
        get
        {
            EnsureByteAligned();
            return bitPosition / 8;
        }
    }

    public bool ReadBoolean() => ReadBits(1) != 0;

    public ulong ReadBits(int bitCount)
    {
        if ((uint)bitCount > 64)
        {
            throw new global::System.ArgumentOutOfRangeException(nameof(bitCount));
        }

        EnsureBits(bitCount);
        ulong value = 0;
        for (int index = 0; index < bitCount; index++)
        {
            int byteIndex = bitPosition >> 3;
            int offset = bitPosition & 7;
            value = (value << 1) | (uint)((source[byteIndex] >> (7 - offset)) & 1);
            bitPosition++;
        }

        return value;
    }

    public sbyte ReadSByte() => unchecked((sbyte)ReadBits(8));

    public byte ReadByte() => (byte)ReadBits(8);

    public short ReadInt16() => unchecked((short)ReadBits(16));

    public ushort ReadUInt16() => (ushort)ReadBits(16);

    public int ReadInt32() => unchecked((int)ReadBits(32));

    public uint ReadUInt32() => (uint)ReadBits(32);

    public ulong ReadUInt64() => ReadBits(64);

    public void ReadReservedBits(int bitCount)
    {
        if (bitCount <= 0)
        {
            throw new global::System.ArgumentOutOfRangeException(nameof(bitCount));
        }

        int remaining = bitCount;
        while (remaining > 0)
        {
            int chunk = global::System.Math.Min(remaining, 64);
            if (ReadBits(chunk) != 0)
            {
                throw new global::LlrpNet.Core.Protocol.LlrpProtocolException(
                    global::LlrpNet.Core.Protocol.LlrpProtocolErrorCode.InvalidReservedBits,
                    "Generated codec encountered non-zero reserved bits.");
            }

            remaining -= chunk;
        }
    }

    public global::System.ReadOnlyMemory<byte> ReadU96() => ReadMemory(12);

    public global::System.ReadOnlyMemory<byte> ReadBytesToEnd()
    {
        EnsureByteAligned();
        int bytePosition = bitPosition / 8;
        return ReadMemory(source.Length - bytePosition);
    }

    public global::System.Collections.Generic.IReadOnlyList<bool> ReadBitVector()
    {
        ushort count = ReadUInt16();
        var values = new bool[count];
        for (int index = 0; index < values.Length; index++)
        {
            values[index] = ReadBoolean();
        }

        ReadVectorPadding(count);
        return values;
    }

    public global::System.Collections.Generic.IReadOnlyList<TEnum> ReadEnumBitVector<TEnum>()
        where TEnum : struct, global::System.Enum
    {
        ushort count = ReadUInt16();
        var values = new TEnum[count];
        for (int index = 0; index < values.Length; index++)
        {
            values[index] = GeneratedCodecRuntime.ReadEnum<TEnum>(ReadBits(1));
        }

        ReadVectorPadding(count);
        return values;
    }

    public global::System.ReadOnlyMemory<byte> ReadByteVector()
    {
        ushort count = ReadUInt16();
        return ReadMemory(count);
    }

    public global::System.Collections.Generic.IReadOnlyList<TEnum> ReadEnumByteVector<TEnum>()
        where TEnum : struct, global::System.Enum
    {
        ushort count = ReadUInt16();
        var values = new TEnum[count];
        for (int index = 0; index < values.Length; index++)
        {
            values[index] = GeneratedCodecRuntime.ReadEnum<TEnum>(ReadByte());
        }

        return values;
    }

    public global::System.Collections.Generic.IReadOnlyList<ushort> ReadUInt16Vector()
    {
        ushort count = ReadUInt16();
        var values = new ushort[count];
        for (int index = 0; index < values.Length; index++)
        {
            values[index] = ReadUInt16();
        }

        return values;
    }

    public global::System.Collections.Generic.IReadOnlyList<TEnum> ReadEnumUInt16Vector<TEnum>()
        where TEnum : struct, global::System.Enum
    {
        ushort count = ReadUInt16();
        var values = new TEnum[count];
        for (int index = 0; index < values.Length; index++)
        {
            values[index] = GeneratedCodecRuntime.ReadEnum<TEnum>(ReadUInt16());
        }

        return values;
    }

    public global::System.Collections.Generic.IReadOnlyList<uint> ReadUInt32Vector()
    {
        ushort count = ReadUInt16();
        var values = new uint[count];
        for (int index = 0; index < values.Length; index++)
        {
            values[index] = ReadUInt32();
        }

        return values;
    }

    public global::System.Collections.Generic.IReadOnlyList<TEnum> ReadEnumUInt32Vector<TEnum>()
        where TEnum : struct, global::System.Enum
    {
        ushort count = ReadUInt16();
        var values = new TEnum[count];
        for (int index = 0; index < values.Length; index++)
        {
            values[index] = GeneratedCodecRuntime.ReadEnum<TEnum>(ReadUInt32());
        }

        return values;
    }

    public string ReadUtf8()
    {
        ushort byteCount = ReadUInt16();
        return GeneratedCodecRuntime.DecodeUtf8(ReadMemory(byteCount).Span);
    }

    private global::System.ReadOnlyMemory<byte> ReadMemory(int byteCount)
    {
        EnsureByteAligned();
        if (byteCount < 0)
        {
            throw new global::System.ArgumentOutOfRangeException(nameof(byteCount));
        }

        int bytePosition = bitPosition / 8;
        if (byteCount > source.Length - bytePosition)
        {
            throw GeneratedCodecRuntime.Truncated(bytePosition, byteCount, source.Length - bytePosition);
        }

        byte[] copy = source.Slice(bytePosition, byteCount).ToArray();
        bitPosition = checked(bitPosition + (byteCount * 8));
        return copy;
    }

    private void ReadVectorPadding(int bitCount)
    {
        int padding = (8 - (bitCount & 7)) & 7;
        if (padding > 0)
        {
            ReadReservedBits(padding);
        }
    }

    private void EnsureBits(int bitCount)
    {
        long remaining = ((long)source.Length * 8) - bitPosition;
        if (bitCount > remaining)
        {
            throw GeneratedCodecRuntime.Truncated(bitPosition / 8, (bitCount + 7) / 8, (int)((remaining + 7) / 8));
        }
    }

    private void EnsureByteAligned()
    {
        if ((bitPosition & 7) != 0)
        {
            throw new global::System.InvalidOperationException("Generated codec reached a non-octet wire boundary.");
        }
    }
}

internal ref struct GeneratedWireWriter
{
    private readonly global::System.Span<byte> destination;
    private int bitPosition;

    public GeneratedWireWriter(global::System.Span<byte> destination)
    {
        this.destination = destination;
        bitPosition = 0;
    }

    public int BytePosition
    {
        get
        {
            EnsureByteAligned();
            return bitPosition / 8;
        }
    }

    public void WriteBoolean(bool value) => WriteBits(value ? 1UL : 0UL, 1);

    public void WriteBits(ulong value, int bitCount)
    {
        if ((uint)bitCount > 64 || (bitCount < 64 && (value >> bitCount) != 0))
        {
            throw new global::System.ArgumentOutOfRangeException(nameof(value), value, "The value does not fit its generated wire field.");
        }

        EnsureBits(bitCount);
        for (int index = bitCount - 1; index >= 0; index--)
        {
            int byteIndex = bitPosition >> 3;
            int offset = bitPosition & 7;
            byte mask = (byte)(0x80 >> offset);
            if (((value >> index) & 1) != 0)
            {
                destination[byteIndex] |= mask;
            }
            else
            {
                destination[byteIndex] &= (byte)~mask;
            }

            bitPosition++;
        }
    }

    public void WriteSByte(sbyte value) => WriteBits(unchecked((byte)value), 8);

    public void WriteByte(byte value) => WriteBits(value, 8);

    public void WriteInt16(short value) => WriteBits(unchecked((ushort)value), 16);

    public void WriteUInt16(ushort value) => WriteBits(value, 16);

    public void WriteInt32(int value) => WriteBits(unchecked((uint)value), 32);

    public void WriteUInt32(uint value) => WriteBits(value, 32);

    public void WriteUInt64(ulong value) => WriteBits(value, 64);

    public void WriteReservedBits(int bitCount)
    {
        if (bitCount <= 0)
        {
            throw new global::System.ArgumentOutOfRangeException(nameof(bitCount));
        }

        int remaining = bitCount;
        while (remaining > 0)
        {
            int chunk = global::System.Math.Min(remaining, 64);
            WriteBits(0, chunk);
            remaining -= chunk;
        }
    }

    public void WriteU96(global::System.ReadOnlyMemory<byte> value)
    {
        if (value.Length != 12)
        {
            throw new global::System.ArgumentException("A u96 field must contain exactly 12 octets.", nameof(value));
        }

        WriteMemory(value);
    }

    public void WriteBytesToEnd(global::System.ReadOnlyMemory<byte> value) => WriteMemory(value);

    public void WriteBitVector(global::System.Collections.Generic.IReadOnlyList<bool> values)
    {
        ValidateCount(values);
        WriteUInt16((ushort)values.Count);
        foreach (bool value in values)
        {
            WriteBoolean(value);
        }

        WriteVectorPadding(values.Count);
    }

    public void WriteEnumBitVector<TEnum>(global::System.Collections.Generic.IReadOnlyList<TEnum> values)
        where TEnum : struct, global::System.Enum
    {
        ValidateCount(values);
        WriteUInt16((ushort)values.Count);
        foreach (TEnum value in values)
        {
            GeneratedCodecRuntime.ValidateEnum(value, nameof(values));
            WriteBits(global::System.Convert.ToUInt64(value, global::System.Globalization.CultureInfo.InvariantCulture), 1);
        }

        WriteVectorPadding(values.Count);
    }

    public void WriteByteVector(global::System.ReadOnlyMemory<byte> value)
    {
        GeneratedCodecRuntime.ValidateUShortCount(value.Length, nameof(value));
        WriteUInt16((ushort)value.Length);
        WriteMemory(value);
    }

    public void WriteEnumByteVector<TEnum>(global::System.Collections.Generic.IReadOnlyList<TEnum> values)
        where TEnum : struct, global::System.Enum
    {
        ValidateCount(values);
        WriteUInt16((ushort)values.Count);
        foreach (TEnum value in values)
        {
            GeneratedCodecRuntime.ValidateEnum(value, nameof(values));
            WriteByte(checked((byte)global::System.Convert.ToUInt64(value, global::System.Globalization.CultureInfo.InvariantCulture)));
        }
    }

    public void WriteUInt16Vector(global::System.Collections.Generic.IReadOnlyList<ushort> values)
    {
        ValidateCount(values);
        WriteUInt16((ushort)values.Count);
        foreach (ushort value in values)
        {
            WriteUInt16(value);
        }
    }

    public void WriteEnumUInt16Vector<TEnum>(global::System.Collections.Generic.IReadOnlyList<TEnum> values)
        where TEnum : struct, global::System.Enum
    {
        ValidateCount(values);
        WriteUInt16((ushort)values.Count);
        foreach (TEnum value in values)
        {
            GeneratedCodecRuntime.ValidateEnum(value, nameof(values));
            WriteUInt16(checked((ushort)global::System.Convert.ToUInt64(value, global::System.Globalization.CultureInfo.InvariantCulture)));
        }
    }

    public void WriteUInt32Vector(global::System.Collections.Generic.IReadOnlyList<uint> values)
    {
        ValidateCount(values);
        WriteUInt16((ushort)values.Count);
        foreach (uint value in values)
        {
            WriteUInt32(value);
        }
    }

    public void WriteEnumUInt32Vector<TEnum>(global::System.Collections.Generic.IReadOnlyList<TEnum> values)
        where TEnum : struct, global::System.Enum
    {
        ValidateCount(values);
        WriteUInt16((ushort)values.Count);
        foreach (TEnum value in values)
        {
            GeneratedCodecRuntime.ValidateEnum(value, nameof(values));
            WriteUInt32(checked((uint)global::System.Convert.ToUInt64(value, global::System.Globalization.CultureInfo.InvariantCulture)));
        }
    }

    public void WriteUtf8(string value)
    {
        global::System.ArgumentNullException.ThrowIfNull(value);
        byte[] encoded = GeneratedCodecRuntime.EncodeUtf8(value);
        GeneratedCodecRuntime.ValidateUShortCount(encoded.Length, nameof(value));
        WriteUInt16((ushort)encoded.Length);
        WriteMemory(encoded);
    }

    private void WriteMemory(global::System.ReadOnlyMemory<byte> value)
    {
        EnsureByteAligned();
        EnsureBits(checked(value.Length * 8));
        value.Span.CopyTo(destination[(bitPosition / 8)..]);
        bitPosition = checked(bitPosition + (value.Length * 8));
    }

    private void WriteVectorPadding(int bitCount)
    {
        int padding = (8 - (bitCount & 7)) & 7;
        if (padding > 0)
        {
            WriteReservedBits(padding);
        }
    }

    private static void ValidateCount<T>(global::System.Collections.Generic.IReadOnlyList<T> values)
    {
        global::System.ArgumentNullException.ThrowIfNull(values);
        GeneratedCodecRuntime.ValidateUShortCount(values.Count, nameof(values));
    }

    private void EnsureBits(int bitCount)
    {
        long remaining = ((long)destination.Length * 8) - bitPosition;
        if (bitCount > remaining)
        {
            throw new global::System.ArgumentException("The generated codec destination is too short.", nameof(destination));
        }
    }

    private void EnsureByteAligned()
    {
        if ((bitPosition & 7) != 0)
        {
            throw new global::System.InvalidOperationException("Generated codec reached a non-octet wire boundary.");
        }
    }
}

internal static class GeneratedCodecRuntime
{
    private static readonly global::System.Text.UTF8Encoding StrictUtf8 = new(false, true);

    public static void ValidateVersion(global::LlrpNet.Core.Protocol.LlrpProtocolVersion version, byte expected)
    {
        if ((byte)version != expected)
        {
            throw new global::System.ArgumentOutOfRangeException(
                nameof(version),
                version,
                $"Generated codec requires LLRP version value {expected}.");
        }
    }

    public static void ValidateDestination(global::System.Span<byte> destination, int expectedLength)
    {
        if (destination.Length != expectedLength)
        {
            throw new global::System.ArgumentException(
                $"Generated codec requires an exact {expectedLength}-octet destination.",
                nameof(destination));
        }
    }

    public static void ValidateDecodedEnd(int offset, int length)
    {
        if (offset != length)
        {
            throw InvalidSequence($"Generated codec left {length - offset} unexpected payload octet(s).");
        }
    }

    public static void ValidateRequiredCount(int count, int minimum, string memberName)
    {
        if (count < minimum)
        {
            throw InvalidSequence($"Member '{memberName}' requires at least {minimum} occurrence(s), but decoded {count}.");
        }
    }

    public static int GetBitVectorLength<T>(global::System.Collections.Generic.IReadOnlyList<T> values)
    {
        global::System.ArgumentNullException.ThrowIfNull(values);
        ValidateUShortCount(values.Count, nameof(values));
        return checked(2 + ((values.Count + 7) / 8));
    }

    public static int GetByteVectorLength(global::System.ReadOnlyMemory<byte> value)
    {
        ValidateUShortCount(value.Length, nameof(value));
        return checked(2 + value.Length);
    }

    public static int GetVectorLength<T>(global::System.Collections.Generic.IReadOnlyList<T> values, int elementLength)
    {
        global::System.ArgumentNullException.ThrowIfNull(values);
        ValidateUShortCount(values.Count, nameof(values));
        return checked(2 + (values.Count * elementLength));
    }

    public static int GetUtf8Length(string value)
    {
        global::System.ArgumentNullException.ThrowIfNull(value);
        int length;
        try
        {
            length = StrictUtf8.GetByteCount(value);
        }
        catch (global::System.Text.EncoderFallbackException exception)
        {
            throw new global::System.ArgumentException("The generated utf8v value is not valid UTF-16 text.", nameof(value), exception);
        }

        ValidateUShortCount(length, nameof(value));
        return checked(2 + length);
    }

    public static TEnum ReadEnum<TEnum>(object rawValue)
        where TEnum : struct, global::System.Enum
    {
        TEnum value = (TEnum)global::System.Enum.ToObject(typeof(TEnum), rawValue);
        if (!global::System.Enum.IsDefined(value))
        {
            throw InvalidSequence($"Undefined {typeof(TEnum).Name} value '{rawValue}'.");
        }

        return value;
    }

    public static void ValidateEnum<TEnum>(TEnum value, string memberName)
        where TEnum : struct, global::System.Enum
    {
        if (!global::System.Enum.IsDefined(value))
        {
            throw new global::System.ArgumentOutOfRangeException(
                memberName,
                value,
                $"Undefined {typeof(TEnum).Name} value.");
        }
    }

    public static bool IsNextParameter(
        global::System.ReadOnlySpan<byte> source,
        ushort expectedType,
        bool matchCustomMetadata,
        uint vendorId,
        uint subtype)
    {
        if (source.IsEmpty)
        {
            return false;
        }

        ushort actualType = (source[0] & 0x80) != 0
            ? global::LlrpNet.Protocol.Parameters.LlrpTvParameterHeader.Decode(source).ParameterType
            : global::LlrpNet.Protocol.Parameters.LlrpTlvParameterHeader.Decode(source).ParameterType;
        if (actualType != expectedType || !matchCustomMetadata)
        {
            return actualType == expectedType;
        }

        global::LlrpNet.Protocol.Parameters.LlrpTlvParameterHeader header =
            global::LlrpNet.Protocol.Parameters.LlrpTlvParameterHeader.Decode(source);
        if (header.ParameterLength > source.Length || header.ParameterLength < 12)
        {
            throw Truncated(0, header.ParameterLength, source.Length);
        }

        uint actualVendor = global::System.Buffers.Binary.BinaryPrimitives.ReadUInt32BigEndian(source[4..]);
        uint actualSubtype = global::System.Buffers.Binary.BinaryPrimitives.ReadUInt32BigEndian(source[8..]);
        return actualVendor == vendorId && actualSubtype == subtype;
    }

    public static bool IsParameterMatch(
        global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry,
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.ILlrpParameter parameter,
        ushort expectedType,
        bool matchCustomMetadata,
        uint vendorId,
        uint subtype)
    {
        global::LlrpNet.Protocol.Registry.LlrpParameterWireIdentity identity =
            registry.GetParameterWireIdentity(version, parameter);
        return identity.ParameterType == expectedType
            && (!matchCustomMetadata
                || (identity.VendorId == vendorId && identity.ParameterSubtype == subtype));
    }

    public static void ValidateParameterMatch(
        global::LlrpNet.Protocol.Parameters.ILlrpParameter parameter,
        string memberName,
        bool matches)
    {
        if (!matches)
        {
            throw new global::System.ArgumentException(
                $"Parameter '{parameter.GetType().FullName}' is not valid for member '{memberName}'.",
                memberName);
        }
    }

    public static T DecodeParameter<T>(
        global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry,
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> source,
        ref int offset)
        where T : class, global::LlrpNet.Protocol.Parameters.ILlrpParameter
    {
        global::LlrpNet.Protocol.Registry.LlrpParameterDecodeResult result = registry.DecodeParameter(version, source[offset..]);
        ValidateConsumed(result.BytesConsumed, source.Length - offset);
        if (result.Parameter is not T typed)
        {
            throw InvalidSequence(
                $"Expected nested parameter {typeof(T).FullName}, but decoded {result.Parameter.GetType().FullName}.");
        }

        offset = checked(offset + result.BytesConsumed);
        return typed;
    }

    public static T DecodeEnvelopeParameter<T>(
        global::LlrpNet.Protocol.Codecs.ILlrpParameterCodec codec,
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> source,
        ref int offset)
        where T : class, global::LlrpNet.Protocol.Parameters.ILlrpParameter
    {
        global::LlrpNet.Protocol.Parameters.LlrpTlvParameterHeader header =
            global::LlrpNet.Protocol.Parameters.LlrpTlvParameterHeader.Decode(source[offset..]);
        ValidateConsumed(header.ParameterLength, source.Length - offset);
        global::System.ReadOnlySpan<byte> payload = source.Slice(
            offset + global::LlrpNet.Protocol.Parameters.LlrpTlvParameterHeader.EncodedLength,
            header.ParameterLength - global::LlrpNet.Protocol.Parameters.LlrpTlvParameterHeader.EncodedLength);
        global::LlrpNet.Protocol.Parameters.ILlrpParameter decoded = codec.Decode(version, payload);
        if (decoded is not T typed)
        {
            throw InvalidSequence($"Envelope codec returned {decoded.GetType().FullName} instead of {typeof(T).FullName}.");
        }

        offset = checked(offset + header.ParameterLength);
        return typed;
    }

    public static int GetEnvelopeParameterLength(
        global::LlrpNet.Protocol.Codecs.ILlrpParameterCodec codec,
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.ILlrpParameter parameter)
    {
        int payloadLength = codec.GetEncodedPayloadLength(version, parameter);
        int completeLength = checked(global::LlrpNet.Protocol.Parameters.LlrpTlvParameterHeader.EncodedLength + payloadLength);
        if (completeLength > ushort.MaxValue)
        {
            throw new global::System.ArgumentOutOfRangeException(nameof(parameter), "TLV parameter exceeds 65535 octets.");
        }

        return completeLength;
    }

    public static int EncodeEnvelopeParameter(
        global::LlrpNet.Protocol.Codecs.ILlrpParameterCodec codec,
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.ILlrpParameter parameter,
        global::System.Span<byte> destination)
    {
        int completeLength = GetEnvelopeParameterLength(codec, version, parameter);
        new global::LlrpNet.Protocol.Parameters.LlrpTlvParameterHeader(1023, (ushort)completeLength)
            .Encode(destination);
        int payloadLength = completeLength - global::LlrpNet.Protocol.Parameters.LlrpTlvParameterHeader.EncodedLength;
        int written = codec.Encode(
            version,
            parameter,
            destination.Slice(global::LlrpNet.Protocol.Parameters.LlrpTlvParameterHeader.EncodedLength, payloadLength));
        if (written != payloadLength)
        {
            throw new global::System.InvalidOperationException("Envelope codec returned an invalid write length.");
        }

        return completeLength;
    }

    public static global::LlrpNet.Core.Protocol.LlrpProtocolException InvalidSequence(string message) =>
        new(global::LlrpNet.Core.Protocol.LlrpProtocolErrorCode.InvalidParameterEncoding, message);

    public static global::LlrpNet.Core.Protocol.LlrpProtocolException Truncated(
        int offset,
        int requested,
        int remaining) =>
        new(
            global::LlrpNet.Core.Protocol.LlrpProtocolErrorCode.TruncatedData,
            $"Generated codec is truncated at byte {offset}: requested {requested}, remaining {remaining}.");

    public static void ValidateUShortCount(int count, string parameterName)
    {
        if ((uint)count > ushort.MaxValue)
        {
            throw new global::System.ArgumentOutOfRangeException(parameterName, count, "Vector length exceeds 65535.");
        }
    }

    public static string DecodeUtf8(global::System.ReadOnlySpan<byte> value)
    {
        try
        {
            return StrictUtf8.GetString(value);
        }
        catch (global::System.Text.DecoderFallbackException exception)
        {
            throw new global::LlrpNet.Core.Protocol.LlrpProtocolException(
                global::LlrpNet.Core.Protocol.LlrpProtocolErrorCode.InvalidParameterEncoding,
                $"Generated utf8v field contains malformed UTF-8: {exception.Message}");
        }
    }

    public static byte[] EncodeUtf8(string value)
    {
        try
        {
            return StrictUtf8.GetBytes(value);
        }
        catch (global::System.Text.EncoderFallbackException exception)
        {
            throw new global::System.ArgumentException("Generated utf8v field is not valid UTF-16 text.", nameof(value), exception);
        }
    }

    private static void ValidateConsumed(int consumed, int remaining)
    {
        if (consumed <= 0 || consumed > remaining)
        {
            throw new global::System.InvalidOperationException(
                $"Nested parameter codec consumed {consumed} octets with {remaining} available.");
        }
    }
}
