// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Codecs.V1_0_1;

internal sealed class ImpinjLinkMonitorConfigurationCodec : global::LlrpNet.Protocol.Codecs.LlrpCustomParameterCodec<global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLinkMonitorConfiguration>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public ImpinjLinkMonitorConfigurationCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLinkMonitorConfiguration Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> data)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(data);
        int offset = 0;
        global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjLinkMonitorMode LinkMonitorMode = GeneratedCodecRuntime.ReadEnum<global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjLinkMonitorMode>(reader.ReadUInt16());
        ushort LinkDownThreshold = reader.ReadUInt16();
        offset += reader.BytePosition;
        var CustomItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Parameters.ILlrpParameter>();
        while (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, false, 0U, 0U))
        {
            CustomItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.ILlrpParameter>(registry, version, data, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(CustomItems.Count, 0, "CustomItems");
        reader = new GeneratedWireReader(data[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, data.Length);
        return new global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLinkMonitorConfiguration(
            LinkMonitorMode,
            LinkDownThreshold,
            CustomItems);
    }

    public override int GetEncodedDataLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLinkMonitorConfiguration parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 4;
        if (parameter.CustomItems is null)
        {
            throw new global::System.ArgumentNullException("CustomItems");
        }
        if (parameter.CustomItems.Count < 0)
        {
            throw new global::System.ArgumentException("Member 'CustomItems' requires cardinality 0..N.", "CustomItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.CustomItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "CustomItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 1023, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        return length;
    }

    public override int EncodeData(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLinkMonitorConfiguration parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedDataLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        GeneratedCodecRuntime.ValidateEnum(parameter.LinkMonitorMode, "LinkMonitorMode"); wireWriter.WriteUInt16(checked((ushort)global::System.Convert.ToUInt64(parameter.LinkMonitorMode, global::System.Globalization.CultureInfo.InvariantCulture)));
        wireWriter.WriteUInt16(parameter.LinkDownThreshold);
        offset += wireWriter.BytePosition;
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.CustomItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
