// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Codecs.V1_0_1;

internal sealed class ImpinjSetQTConfigCodec : global::LlrpNet.Protocol.Codecs.LlrpCustomParameterCodec<global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjSetQTConfig>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public ImpinjSetQTConfigCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjSetQTConfig Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> data)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(data);
        int offset = 0;
        ushort OpSpecID = reader.ReadUInt16();
        uint AccessPassword = reader.ReadUInt32();
        global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjQTDataProfile DataProfile = GeneratedCodecRuntime.ReadEnum<global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjQTDataProfile>(reader.ReadByte());
        global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjQTAccessRange AccessRange = GeneratedCodecRuntime.ReadEnum<global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjQTAccessRange>(reader.ReadByte());
        global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjQTPersistence Persistence = GeneratedCodecRuntime.ReadEnum<global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjQTPersistence>(reader.ReadByte());
        reader.ReadReservedBits(32);
        offset += reader.BytePosition;
        var CustomItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Parameters.ILlrpParameter>();
        while (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, false, 0U, 0U))
        {
            CustomItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.ILlrpParameter>(registry, version, data, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(CustomItems.Count, 0, "CustomItems");
        reader = new GeneratedWireReader(data[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, data.Length);
        return new global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjSetQTConfig(
            OpSpecID,
            AccessPassword,
            DataProfile,
            AccessRange,
            Persistence,
            CustomItems);
    }

    public override int GetEncodedDataLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjSetQTConfig parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 13;
        if (parameter.CustomItems is null)
        {
            throw new global::System.ArgumentNullException("CustomItems");
        }
        if (parameter.CustomItems.Count < 0)
        {
            throw new global::System.ArgumentException("Member 'CustomItems' requires cardinality 0..N.", "CustomItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.CustomItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "CustomItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 1023, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        return length;
    }

    public override int EncodeData(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjSetQTConfig parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedDataLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteUInt16(parameter.OpSpecID);
        wireWriter.WriteUInt32(parameter.AccessPassword);
        GeneratedCodecRuntime.ValidateEnum(parameter.DataProfile, "DataProfile"); wireWriter.WriteByte(checked((byte)global::System.Convert.ToUInt64(parameter.DataProfile, global::System.Globalization.CultureInfo.InvariantCulture)));
        GeneratedCodecRuntime.ValidateEnum(parameter.AccessRange, "AccessRange"); wireWriter.WriteByte(checked((byte)global::System.Convert.ToUInt64(parameter.AccessRange, global::System.Globalization.CultureInfo.InvariantCulture)));
        GeneratedCodecRuntime.ValidateEnum(parameter.Persistence, "Persistence"); wireWriter.WriteByte(checked((byte)global::System.Convert.ToUInt64(parameter.Persistence, global::System.Globalization.CultureInfo.InvariantCulture)));
        wireWriter.WriteReservedBits(32);
        offset += wireWriter.BytePosition;
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.CustomItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
