// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Codecs.V1_0_1;

internal sealed class ImpinjAntennaConfigurationCodec : global::LlrpNet.Protocol.Codecs.LlrpCustomParameterCodec<global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjAntennaConfiguration>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public ImpinjAntennaConfigurationCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjAntennaConfiguration Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> data)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(data);
        int offset = 0;
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjAntennaEventHysteresis? ImpinjAntennaEventHysteresis = null;
        if (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, true, 25882U, 1526U))
        {
            ImpinjAntennaEventHysteresis = GeneratedCodecRuntime.DecodeParameter<global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjAntennaEventHysteresis>(registry, version, data, ref offset);
        }
        reader = new GeneratedWireReader(data[offset..]);
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjAntennaEventConfiguration? ImpinjAntennaEventConfiguration = null;
        if (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, true, 25882U, 1576U))
        {
            ImpinjAntennaEventConfiguration = GeneratedCodecRuntime.DecodeParameter<global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjAntennaEventConfiguration>(registry, version, data, ref offset);
        }
        reader = new GeneratedWireReader(data[offset..]);
        var CustomItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Parameters.ILlrpParameter>();
        while (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, false, 0U, 0U))
        {
            CustomItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.ILlrpParameter>(registry, version, data, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(CustomItems.Count, 0, "CustomItems");
        reader = new GeneratedWireReader(data[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, data.Length);
        return new global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjAntennaConfiguration(
            ImpinjAntennaEventHysteresis,
            ImpinjAntennaEventConfiguration,
            CustomItems);
    }

    public override int GetEncodedDataLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjAntennaConfiguration parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 0;
        if (parameter.ImpinjAntennaEventHysteresis is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.ImpinjAntennaEventHysteresis, "ImpinjAntennaEventHysteresis", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.ImpinjAntennaEventHysteresis, 1023, true, 25882U, 1526U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.ImpinjAntennaEventHysteresis));
        }
        if (parameter.ImpinjAntennaEventConfiguration is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.ImpinjAntennaEventConfiguration, "ImpinjAntennaEventConfiguration", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.ImpinjAntennaEventConfiguration, 1023, true, 25882U, 1576U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.ImpinjAntennaEventConfiguration));
        }
        if (parameter.CustomItems is null)
        {
            throw new global::System.ArgumentNullException("CustomItems");
        }
        if (parameter.CustomItems.Count < 0)
        {
            throw new global::System.ArgumentException("Member 'CustomItems' requires cardinality 0..N.", "CustomItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.CustomItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "CustomItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 1023, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        return length;
    }

    public override int EncodeData(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjAntennaConfiguration parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedDataLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        if (parameter.ImpinjAntennaEventHysteresis is not null)
        {
            offset += registry.EncodeParameter(version, parameter.ImpinjAntennaEventHysteresis, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (parameter.ImpinjAntennaEventConfiguration is not null)
        {
            offset += registry.EncodeParameter(version, parameter.ImpinjAntennaEventConfiguration, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.CustomItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
