// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Codecs.V1_0_1;

internal sealed class ImpinjLISpecCodec : global::LlrpNet.Protocol.Codecs.LlrpCustomParameterCodec<global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLISpec>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public ImpinjLISpecCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLISpec Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> data)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(data);
        int offset = 0;
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLocationConfig? ImpinjLocationConfig = null;
        if (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, true, 25882U, 1542U))
        {
            ImpinjLocationConfig = GeneratedCodecRuntime.DecodeParameter<global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLocationConfig>(registry, version, data, ref offset);
        }
        reader = new GeneratedWireReader(data[offset..]);
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjC1G2LocationConfig? ImpinjC1G2LocationConfig = null;
        if (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, true, 25882U, 1543U))
        {
            ImpinjC1G2LocationConfig = GeneratedCodecRuntime.DecodeParameter<global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjC1G2LocationConfig>(registry, version, data, ref offset);
        }
        reader = new GeneratedWireReader(data[offset..]);
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLocationReporting? ImpinjLocationReporting = null;
        if (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, true, 25882U, 1544U))
        {
            ImpinjLocationReporting = GeneratedCodecRuntime.DecodeParameter<global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLocationReporting>(registry, version, data, ref offset);
        }
        reader = new GeneratedWireReader(data[offset..]);
        var CustomItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Parameters.ILlrpParameter>();
        while (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, false, 0U, 0U))
        {
            CustomItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.ILlrpParameter>(registry, version, data, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(CustomItems.Count, 0, "CustomItems");
        reader = new GeneratedWireReader(data[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, data.Length);
        return new global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLISpec(
            ImpinjLocationConfig,
            ImpinjC1G2LocationConfig,
            ImpinjLocationReporting,
            CustomItems);
    }

    public override int GetEncodedDataLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLISpec parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 0;
        if (parameter.ImpinjLocationConfig is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.ImpinjLocationConfig, "ImpinjLocationConfig", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.ImpinjLocationConfig, 1023, true, 25882U, 1542U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.ImpinjLocationConfig));
        }
        if (parameter.ImpinjC1G2LocationConfig is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.ImpinjC1G2LocationConfig, "ImpinjC1G2LocationConfig", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.ImpinjC1G2LocationConfig, 1023, true, 25882U, 1543U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.ImpinjC1G2LocationConfig));
        }
        if (parameter.ImpinjLocationReporting is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.ImpinjLocationReporting, "ImpinjLocationReporting", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.ImpinjLocationReporting, 1023, true, 25882U, 1544U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.ImpinjLocationReporting));
        }
        if (parameter.CustomItems is null)
        {
            throw new global::System.ArgumentNullException("CustomItems");
        }
        if (parameter.CustomItems.Count < 0)
        {
            throw new global::System.ArgumentException("Member 'CustomItems' requires cardinality 0..N.", "CustomItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.CustomItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "CustomItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 1023, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        return length;
    }

    public override int EncodeData(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLISpec parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedDataLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        if (parameter.ImpinjLocationConfig is not null)
        {
            offset += registry.EncodeParameter(version, parameter.ImpinjLocationConfig, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (parameter.ImpinjC1G2LocationConfig is not null)
        {
            offset += registry.EncodeParameter(version, parameter.ImpinjC1G2LocationConfig, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (parameter.ImpinjLocationReporting is not null)
        {
            offset += registry.EncodeParameter(version, parameter.ImpinjLocationReporting, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.CustomItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
