// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Codecs.V1_0_1;

internal sealed class ImpinjLocationConfigCodec : global::LlrpNet.Protocol.Codecs.LlrpCustomParameterCodec<global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLocationConfig>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public ImpinjLocationConfigCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLocationConfig Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> data)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(data);
        int offset = 0;
        ushort ComputeWindowSeconds = reader.ReadUInt16();
        ushort TagAgeIntervalSeconds = reader.ReadUInt16();
        ushort UpdateIntervalSeconds = reader.ReadUInt16();
        offset += reader.BytePosition;
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjDisabledAntennas? ImpinjDisabledAntennas = null;
        if (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, true, 25882U, 1565U))
        {
            ImpinjDisabledAntennas = GeneratedCodecRuntime.DecodeParameter<global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjDisabledAntennas>(registry, version, data, ref offset);
        }
        reader = new GeneratedWireReader(data[offset..]);
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLocationAlgorithmControl? ImpinjLocationAlgorithmControl = null;
        if (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, true, 25882U, 1581U))
        {
            ImpinjLocationAlgorithmControl = GeneratedCodecRuntime.DecodeParameter<global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLocationAlgorithmControl>(registry, version, data, ref offset);
        }
        reader = new GeneratedWireReader(data[offset..]);
        var CustomItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Parameters.ILlrpParameter>();
        while (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, false, 0U, 0U))
        {
            CustomItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.ILlrpParameter>(registry, version, data, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(CustomItems.Count, 0, "CustomItems");
        reader = new GeneratedWireReader(data[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, data.Length);
        return new global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLocationConfig(
            ComputeWindowSeconds,
            TagAgeIntervalSeconds,
            UpdateIntervalSeconds,
            ImpinjDisabledAntennas,
            ImpinjLocationAlgorithmControl,
            CustomItems);
    }

    public override int GetEncodedDataLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLocationConfig parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 6;
        if (parameter.ImpinjDisabledAntennas is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.ImpinjDisabledAntennas, "ImpinjDisabledAntennas", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.ImpinjDisabledAntennas, 1023, true, 25882U, 1565U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.ImpinjDisabledAntennas));
        }
        if (parameter.ImpinjLocationAlgorithmControl is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.ImpinjLocationAlgorithmControl, "ImpinjLocationAlgorithmControl", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.ImpinjLocationAlgorithmControl, 1023, true, 25882U, 1581U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.ImpinjLocationAlgorithmControl));
        }
        if (parameter.CustomItems is null)
        {
            throw new global::System.ArgumentNullException("CustomItems");
        }
        if (parameter.CustomItems.Count < 0)
        {
            throw new global::System.ArgumentException("Member 'CustomItems' requires cardinality 0..N.", "CustomItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.CustomItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "CustomItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 1023, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        return length;
    }

    public override int EncodeData(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLocationConfig parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedDataLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteUInt16(parameter.ComputeWindowSeconds);
        wireWriter.WriteUInt16(parameter.TagAgeIntervalSeconds);
        wireWriter.WriteUInt16(parameter.UpdateIntervalSeconds);
        offset += wireWriter.BytePosition;
        if (parameter.ImpinjDisabledAntennas is not null)
        {
            offset += registry.EncodeParameter(version, parameter.ImpinjDisabledAntennas, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (parameter.ImpinjLocationAlgorithmControl is not null)
        {
            offset += registry.EncodeParameter(version, parameter.ImpinjLocationAlgorithmControl, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.CustomItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
