// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Codecs.V1_0_1;

internal sealed class ImpinjLocationReportDataCodec : global::LlrpNet.Protocol.Codecs.LlrpCustomParameterCodec<global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLocationReportData>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public ImpinjLocationReportDataCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLocationReportData Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> data)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(data);
        int offset = 0;
        ulong LastSeenTimestampUTC = reader.ReadUInt64();
        int LocXCentimeters = reader.ReadInt32();
        int LocYCentimeters = reader.ReadInt32();
        global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjLocationReportType Type = GeneratedCodecRuntime.ReadEnum<global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjLocationReportType>(reader.ReadByte());
        offset += reader.BytePosition;
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLocationConfidence? ImpinjLocationConfidence = null;
        if (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, true, 25882U, 1553U))
        {
            ImpinjLocationConfidence = GeneratedCodecRuntime.DecodeParameter<global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLocationConfidence>(registry, version, data, ref offset);
        }
        if (ImpinjLocationConfidence is null)
        {
            throw GeneratedCodecRuntime.InvalidSequence("Required parameter 'ImpinjLocationConfidence' is missing.");
        }
        reader = new GeneratedWireReader(data[offset..]);
        var CustomItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Parameters.ILlrpParameter>();
        while (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, false, 0U, 0U))
        {
            CustomItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.ILlrpParameter>(registry, version, data, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(CustomItems.Count, 0, "CustomItems");
        reader = new GeneratedWireReader(data[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, data.Length);
        return new global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLocationReportData(
            LastSeenTimestampUTC,
            LocXCentimeters,
            LocYCentimeters,
            Type,
            ImpinjLocationConfidence!,
            CustomItems);
    }

    public override int GetEncodedDataLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLocationReportData parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 17;
        if (parameter.ImpinjLocationConfidence is null)
        {
            throw new global::System.ArgumentNullException("ImpinjLocationConfidence");
        }
        GeneratedCodecRuntime.ValidateParameterMatch(parameter.ImpinjLocationConfidence!, "ImpinjLocationConfidence", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.ImpinjLocationConfidence!, 1023, true, 25882U, 1553U));
        length = checked(length + registry.GetEncodedParameterLength(version, parameter.ImpinjLocationConfidence!));
        if (parameter.CustomItems is null)
        {
            throw new global::System.ArgumentNullException("CustomItems");
        }
        if (parameter.CustomItems.Count < 0)
        {
            throw new global::System.ArgumentException("Member 'CustomItems' requires cardinality 0..N.", "CustomItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.CustomItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "CustomItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 1023, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        return length;
    }

    public override int EncodeData(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjLocationReportData parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedDataLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteUInt64(parameter.LastSeenTimestampUTC);
        wireWriter.WriteInt32(parameter.LocXCentimeters);
        wireWriter.WriteInt32(parameter.LocYCentimeters);
        GeneratedCodecRuntime.ValidateEnum(parameter.Type, "Type"); wireWriter.WriteByte(checked((byte)global::System.Convert.ToUInt64(parameter.Type, global::System.Globalization.CultureInfo.InvariantCulture)));
        offset += wireWriter.BytePosition;
        offset += registry.EncodeParameter(version, parameter.ImpinjLocationConfidence!, destination[offset..]);
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.CustomItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
