// <auto-generated />
#nullable enable

namespace LlrpSdk.Extensions.Impinj.Codecs.V1_0_1;

internal sealed class ImpinjC1G2DirectionConfigCodec : global::LlrpNet.Protocol.Codecs.LlrpCustomParameterCodec<global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjC1G2DirectionConfig>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public ImpinjC1G2DirectionConfigCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjC1G2DirectionConfig Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> data)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(data);
        int offset = 0;
        global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjDirectionRFMode RFMode = GeneratedCodecRuntime.ReadEnum<global::LlrpSdk.Extensions.Impinj.Enumerations.V1_0_1.ImpinjDirectionRFMode>(reader.ReadByte());
        offset += reader.BytePosition;
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjTransmitPower? ImpinjTransmitPower = null;
        if (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, true, 25882U, 1561U))
        {
            ImpinjTransmitPower = GeneratedCodecRuntime.DecodeParameter<global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjTransmitPower>(registry, version, data, ref offset);
        }
        reader = new GeneratedWireReader(data[offset..]);
        var C1G2FilterItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Parameters.V1_0_1.C1G2Filter>();
        while (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 331, false, 0U, 0U))
        {
            C1G2FilterItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.C1G2Filter>(registry, version, data, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(C1G2FilterItems.Count, 0, "C1G2FilterItems");
        reader = new GeneratedWireReader(data[offset..]);
        var CustomItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Parameters.ILlrpParameter>();
        while (offset < data.Length && GeneratedCodecRuntime.IsNextParameter(data[offset..], 1023, false, 0U, 0U))
        {
            CustomItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.ILlrpParameter>(registry, version, data, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(CustomItems.Count, 0, "CustomItems");
        reader = new GeneratedWireReader(data[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, data.Length);
        return new global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjC1G2DirectionConfig(
            RFMode,
            ImpinjTransmitPower,
            C1G2FilterItems,
            CustomItems);
    }

    public override int GetEncodedDataLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjC1G2DirectionConfig parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 1;
        if (parameter.ImpinjTransmitPower is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.ImpinjTransmitPower, "ImpinjTransmitPower", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.ImpinjTransmitPower, 1023, true, 25882U, 1561U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.ImpinjTransmitPower));
        }
        if (parameter.C1G2FilterItems is null)
        {
            throw new global::System.ArgumentNullException("C1G2FilterItems");
        }
        if (parameter.C1G2FilterItems.Count < 0)
        {
            throw new global::System.ArgumentException("Member 'C1G2FilterItems' requires cardinality 0..N.", "C1G2FilterItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.C1G2FilterItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "C1G2FilterItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 331, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        if (parameter.CustomItems is null)
        {
            throw new global::System.ArgumentNullException("CustomItems");
        }
        if (parameter.CustomItems.Count < 0)
        {
            throw new global::System.ArgumentException("Member 'CustomItems' requires cardinality 0..N.", "CustomItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.CustomItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "CustomItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 1023, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        return length;
    }

    public override int EncodeData(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpSdk.Extensions.Impinj.Parameters.V1_0_1.ImpinjC1G2DirectionConfig parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedDataLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        GeneratedCodecRuntime.ValidateEnum(parameter.RFMode, "RFMode"); wireWriter.WriteByte(checked((byte)global::System.Convert.ToUInt64(parameter.RFMode, global::System.Globalization.CultureInfo.InvariantCulture)));
        offset += wireWriter.BytePosition;
        if (parameter.ImpinjTransmitPower is not null)
        {
            offset += registry.EncodeParameter(version, parameter.ImpinjTransmitPower, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.C1G2FilterItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.CustomItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
