// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V1_0_1;

internal sealed class GeneralDeviceCapabilitiesCodec : global::LlrpNet.Protocol.Codecs.LlrpParameterCodec<global::LlrpNet.Protocol.Parameters.V1_0_1.GeneralDeviceCapabilities>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public GeneralDeviceCapabilitiesCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Parameters.V1_0_1.GeneralDeviceCapabilities Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(payload);
        int offset = 0;
        ushort MaxNumberOfAntennaSupported = reader.ReadUInt16();
        bool CanSetAntennaProperties = reader.ReadBoolean();
        bool HasUTCClockCapability = reader.ReadBoolean();
        reader.ReadReservedBits(14);
        uint DeviceManufacturerName = reader.ReadUInt32();
        uint ModelName = reader.ReadUInt32();
        string ReaderFirmwareVersion = reader.ReadUtf8();
        offset += reader.BytePosition;
        var ReceiveSensitivityTableEntryItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Parameters.V1_0_1.ReceiveSensitivityTableEntry>();
        while (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 139, false, 0U, 0U))
        {
            ReceiveSensitivityTableEntryItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.ReceiveSensitivityTableEntry>(registry, version, payload, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(ReceiveSensitivityTableEntryItems.Count, 1, "ReceiveSensitivityTableEntryItems");
        reader = new GeneratedWireReader(payload[offset..]);
        var PerAntennaReceiveSensitivityRangeItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Parameters.V1_0_1.PerAntennaReceiveSensitivityRange>();
        while (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 149, false, 0U, 0U))
        {
            PerAntennaReceiveSensitivityRangeItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.PerAntennaReceiveSensitivityRange>(registry, version, payload, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(PerAntennaReceiveSensitivityRangeItems.Count, 0, "PerAntennaReceiveSensitivityRangeItems");
        reader = new GeneratedWireReader(payload[offset..]);
        global::LlrpNet.Protocol.Parameters.V1_0_1.GPIOCapabilities? GPIOCapabilities = null;
        if (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 141, false, 0U, 0U))
        {
            GPIOCapabilities = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.GPIOCapabilities>(registry, version, payload, ref offset);
        }
        if (GPIOCapabilities is null)
        {
            throw GeneratedCodecRuntime.InvalidSequence("Required parameter 'GPIOCapabilities' is missing.");
        }
        reader = new GeneratedWireReader(payload[offset..]);
        var PerAntennaAirProtocolItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Parameters.V1_0_1.PerAntennaAirProtocol>();
        while (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 140, false, 0U, 0U))
        {
            PerAntennaAirProtocolItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.PerAntennaAirProtocol>(registry, version, payload, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(PerAntennaAirProtocolItems.Count, 1, "PerAntennaAirProtocolItems");
        reader = new GeneratedWireReader(payload[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Parameters.V1_0_1.GeneralDeviceCapabilities(
            MaxNumberOfAntennaSupported,
            CanSetAntennaProperties,
            HasUTCClockCapability,
            DeviceManufacturerName,
            ModelName,
            ReaderFirmwareVersion,
            ReceiveSensitivityTableEntryItems,
            PerAntennaReceiveSensitivityRangeItems,
            GPIOCapabilities!,
            PerAntennaAirProtocolItems);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_0_1.GeneralDeviceCapabilities parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 12;
        length = checked(length + GeneratedCodecRuntime.GetUtf8Length(parameter.ReaderFirmwareVersion));
        if (parameter.ReceiveSensitivityTableEntryItems is null)
        {
            throw new global::System.ArgumentNullException("ReceiveSensitivityTableEntryItems");
        }
        if (parameter.ReceiveSensitivityTableEntryItems.Count < 1)
        {
            throw new global::System.ArgumentException("Member 'ReceiveSensitivityTableEntryItems' requires cardinality 1..N.", "ReceiveSensitivityTableEntryItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.ReceiveSensitivityTableEntryItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "ReceiveSensitivityTableEntryItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 139, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        if (parameter.PerAntennaReceiveSensitivityRangeItems is null)
        {
            throw new global::System.ArgumentNullException("PerAntennaReceiveSensitivityRangeItems");
        }
        if (parameter.PerAntennaReceiveSensitivityRangeItems.Count < 0)
        {
            throw new global::System.ArgumentException("Member 'PerAntennaReceiveSensitivityRangeItems' requires cardinality 0..N.", "PerAntennaReceiveSensitivityRangeItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.PerAntennaReceiveSensitivityRangeItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "PerAntennaReceiveSensitivityRangeItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 149, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        if (parameter.GPIOCapabilities is null)
        {
            throw new global::System.ArgumentNullException("GPIOCapabilities");
        }
        GeneratedCodecRuntime.ValidateParameterMatch(parameter.GPIOCapabilities!, "GPIOCapabilities", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.GPIOCapabilities!, 141, false, 0U, 0U));
        length = checked(length + registry.GetEncodedParameterLength(version, parameter.GPIOCapabilities!));
        if (parameter.PerAntennaAirProtocolItems is null)
        {
            throw new global::System.ArgumentNullException("PerAntennaAirProtocolItems");
        }
        if (parameter.PerAntennaAirProtocolItems.Count < 1)
        {
            throw new global::System.ArgumentException("Member 'PerAntennaAirProtocolItems' requires cardinality 1..N.", "PerAntennaAirProtocolItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.PerAntennaAirProtocolItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "PerAntennaAirProtocolItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 140, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_0_1.GeneralDeviceCapabilities parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteUInt16(parameter.MaxNumberOfAntennaSupported);
        wireWriter.WriteBoolean(parameter.CanSetAntennaProperties);
        wireWriter.WriteBoolean(parameter.HasUTCClockCapability);
        wireWriter.WriteReservedBits(14);
        wireWriter.WriteUInt32(parameter.DeviceManufacturerName);
        wireWriter.WriteUInt32(parameter.ModelName);
        wireWriter.WriteUtf8(parameter.ReaderFirmwareVersion);
        offset += wireWriter.BytePosition;
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.ReceiveSensitivityTableEntryItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.PerAntennaReceiveSensitivityRangeItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        offset += registry.EncodeParameter(version, parameter.GPIOCapabilities!, destination[offset..]);
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.PerAntennaAirProtocolItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
