// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V1_0_1;

internal sealed class UHFBandCapabilitiesCodec : global::LlrpNet.Protocol.Codecs.LlrpParameterCodec<global::LlrpNet.Protocol.Parameters.V1_0_1.UHFBandCapabilities>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public UHFBandCapabilitiesCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Parameters.V1_0_1.UHFBandCapabilities Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(payload);
        int offset = 0;
        var TransmitPowerLevelTableEntryItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Parameters.V1_0_1.TransmitPowerLevelTableEntry>();
        while (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 145, false, 0U, 0U))
        {
            TransmitPowerLevelTableEntryItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.TransmitPowerLevelTableEntry>(registry, version, payload, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(TransmitPowerLevelTableEntryItems.Count, 1, "TransmitPowerLevelTableEntryItems");
        reader = new GeneratedWireReader(payload[offset..]);
        global::LlrpNet.Protocol.Parameters.V1_0_1.FrequencyInformation? FrequencyInformation = null;
        if (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 146, false, 0U, 0U))
        {
            FrequencyInformation = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.FrequencyInformation>(registry, version, payload, ref offset);
        }
        if (FrequencyInformation is null)
        {
            throw GeneratedCodecRuntime.InvalidSequence("Required parameter 'FrequencyInformation' is missing.");
        }
        reader = new GeneratedWireReader(payload[offset..]);
        var AirProtocolUHFRFModeTableItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Choices.V1_0_1.IAirProtocolUHFRFModeTable>();
        while (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 328, false, 0U, 0U))
        {
            AirProtocolUHFRFModeTableItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Choices.V1_0_1.IAirProtocolUHFRFModeTable>(registry, version, payload, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(AirProtocolUHFRFModeTableItems.Count, 1, "AirProtocolUHFRFModeTableItems");
        reader = new GeneratedWireReader(payload[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Parameters.V1_0_1.UHFBandCapabilities(
            TransmitPowerLevelTableEntryItems,
            FrequencyInformation!,
            AirProtocolUHFRFModeTableItems);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_0_1.UHFBandCapabilities parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 0;
        if (parameter.TransmitPowerLevelTableEntryItems is null)
        {
            throw new global::System.ArgumentNullException("TransmitPowerLevelTableEntryItems");
        }
        if (parameter.TransmitPowerLevelTableEntryItems.Count < 1)
        {
            throw new global::System.ArgumentException("Member 'TransmitPowerLevelTableEntryItems' requires cardinality 1..N.", "TransmitPowerLevelTableEntryItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.TransmitPowerLevelTableEntryItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "TransmitPowerLevelTableEntryItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 145, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        if (parameter.FrequencyInformation is null)
        {
            throw new global::System.ArgumentNullException("FrequencyInformation");
        }
        GeneratedCodecRuntime.ValidateParameterMatch(parameter.FrequencyInformation!, "FrequencyInformation", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.FrequencyInformation!, 146, false, 0U, 0U));
        length = checked(length + registry.GetEncodedParameterLength(version, parameter.FrequencyInformation!));
        if (parameter.AirProtocolUHFRFModeTableItems is null)
        {
            throw new global::System.ArgumentNullException("AirProtocolUHFRFModeTableItems");
        }
        if (parameter.AirProtocolUHFRFModeTableItems.Count < 1)
        {
            throw new global::System.ArgumentException("Member 'AirProtocolUHFRFModeTableItems' requires cardinality 1..N.", "AirProtocolUHFRFModeTableItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.AirProtocolUHFRFModeTableItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "AirProtocolUHFRFModeTableItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 328, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_0_1.UHFBandCapabilities parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.TransmitPowerLevelTableEntryItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        offset += registry.EncodeParameter(version, parameter.FrequencyInformation!, destination[offset..]);
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.AirProtocolUHFRFModeTableItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
