// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V1_0_1;

internal sealed class PeriodicTriggerValueCodec : global::LlrpNet.Protocol.Codecs.LlrpParameterCodec<global::LlrpNet.Protocol.Parameters.V1_0_1.PeriodicTriggerValue>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public PeriodicTriggerValueCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Parameters.V1_0_1.PeriodicTriggerValue Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(payload);
        int offset = 0;
        uint Offset = reader.ReadUInt32();
        uint Period = reader.ReadUInt32();
        offset += reader.BytePosition;
        global::LlrpNet.Protocol.Parameters.V1_0_1.UTCTimestamp? UTCTimestamp = null;
        if (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 128, false, 0U, 0U))
        {
            UTCTimestamp = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.UTCTimestamp>(registry, version, payload, ref offset);
        }
        reader = new GeneratedWireReader(payload[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Parameters.V1_0_1.PeriodicTriggerValue(
            Offset,
            Period,
            UTCTimestamp);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_0_1.PeriodicTriggerValue parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 8;
        if (parameter.UTCTimestamp is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.UTCTimestamp, "UTCTimestamp", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.UTCTimestamp, 128, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.UTCTimestamp));
        }
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_0_1.PeriodicTriggerValue parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        wireWriter.WriteUInt32(parameter.Offset);
        wireWriter.WriteUInt32(parameter.Period);
        offset += wireWriter.BytePosition;
        if (parameter.UTCTimestamp is not null)
        {
            offset += registry.EncodeParameter(version, parameter.UTCTimestamp, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
