// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V1_0_1;

internal sealed class ROSpecStopTriggerCodec : global::LlrpNet.Protocol.Codecs.LlrpParameterCodec<global::LlrpNet.Protocol.Parameters.V1_0_1.ROSpecStopTrigger>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public ROSpecStopTriggerCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Parameters.V1_0_1.ROSpecStopTrigger Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(payload);
        int offset = 0;
        global::LlrpNet.Protocol.Enumerations.V1_0_1.ROSpecStopTriggerType ROSpecStopTriggerType = GeneratedCodecRuntime.ReadEnum<global::LlrpNet.Protocol.Enumerations.V1_0_1.ROSpecStopTriggerType>(reader.ReadByte());
        uint DurationTriggerValue = reader.ReadUInt32();
        offset += reader.BytePosition;
        global::LlrpNet.Protocol.Parameters.V1_0_1.GPITriggerValue? GPITriggerValue = null;
        if (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 181, false, 0U, 0U))
        {
            GPITriggerValue = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.GPITriggerValue>(registry, version, payload, ref offset);
        }
        reader = new GeneratedWireReader(payload[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Parameters.V1_0_1.ROSpecStopTrigger(
            ROSpecStopTriggerType,
            DurationTriggerValue,
            GPITriggerValue);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_0_1.ROSpecStopTrigger parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 5;
        if (parameter.GPITriggerValue is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.GPITriggerValue, "GPITriggerValue", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.GPITriggerValue, 181, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.GPITriggerValue));
        }
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_0_1.ROSpecStopTrigger parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        GeneratedCodecRuntime.ValidateEnum(parameter.ROSpecStopTriggerType, "ROSpecStopTriggerType"); wireWriter.WriteByte(checked((byte)global::System.Convert.ToUInt64(parameter.ROSpecStopTriggerType, global::System.Globalization.CultureInfo.InvariantCulture)));
        wireWriter.WriteUInt32(parameter.DurationTriggerValue);
        offset += wireWriter.BytePosition;
        if (parameter.GPITriggerValue is not null)
        {
            offset += registry.EncodeParameter(version, parameter.GPITriggerValue, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
