// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V1_0_1;

internal sealed class AISpecStopTriggerCodec : global::LlrpNet.Protocol.Codecs.LlrpParameterCodec<global::LlrpNet.Protocol.Parameters.V1_0_1.AISpecStopTrigger>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public AISpecStopTriggerCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Parameters.V1_0_1.AISpecStopTrigger Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(payload);
        global::LlrpNet.Protocol.Enumerations.V1_0_1.AISpecStopTriggerType AISpecStopTriggerType = GeneratedCodecRuntime.ReadEnum<global::LlrpNet.Protocol.Enumerations.V1_0_1.AISpecStopTriggerType>(reader.ReadByte());
        uint DurationTrigger = reader.ReadUInt32();
        int offset = reader.BytePosition;
        global::LlrpNet.Protocol.Parameters.V1_0_1.GPITriggerValue? GPITriggerValue = null;
        if (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 181, false, 0U, 0U))
        {
            GPITriggerValue = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.GPITriggerValue>(registry, version, payload, ref offset);
        }
        global::LlrpNet.Protocol.Parameters.V1_0_1.TagObservationTrigger? TagObservationTrigger = null;
        if (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 185, false, 0U, 0U))
        {
            TagObservationTrigger = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.TagObservationTrigger>(registry, version, payload, ref offset);
        }
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Parameters.V1_0_1.AISpecStopTrigger(
            AISpecStopTriggerType,
            DurationTrigger,
            GPITriggerValue,
            TagObservationTrigger);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_0_1.AISpecStopTrigger parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 5;
        if (parameter.GPITriggerValue is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.GPITriggerValue, "GPITriggerValue", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.GPITriggerValue, 181, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.GPITriggerValue));
        }
        if (parameter.TagObservationTrigger is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.TagObservationTrigger, "TagObservationTrigger", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.TagObservationTrigger, 185, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.TagObservationTrigger));
        }
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_0_1.AISpecStopTrigger parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        GeneratedCodecRuntime.ValidateEnum(parameter.AISpecStopTriggerType, "AISpecStopTriggerType"); wireWriter.WriteByte(checked((byte)global::System.Convert.ToUInt64(parameter.AISpecStopTriggerType, global::System.Globalization.CultureInfo.InvariantCulture)));
        wireWriter.WriteUInt32(parameter.DurationTrigger);
        int offset = wireWriter.BytePosition;
        if (parameter.GPITriggerValue is not null)
        {
            offset += registry.EncodeParameter(version, parameter.GPITriggerValue, destination[offset..]);
        }
        if (parameter.TagObservationTrigger is not null)
        {
            offset += registry.EncodeParameter(version, parameter.TagObservationTrigger, destination[offset..]);
        }
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
