// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V1_0_1;

internal sealed class AccessSpecCodec : global::LlrpNet.Protocol.Codecs.LlrpParameterCodec<global::LlrpNet.Protocol.Parameters.V1_0_1.AccessSpec>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public AccessSpecCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Parameters.V1_0_1.AccessSpec Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(payload);
        uint AccessSpecID = reader.ReadUInt32();
        ushort AntennaID = reader.ReadUInt16();
        global::LlrpNet.Protocol.Enumerations.V1_0_1.AirProtocols ProtocolID = GeneratedCodecRuntime.ReadEnum<global::LlrpNet.Protocol.Enumerations.V1_0_1.AirProtocols>(reader.ReadByte());
        global::LlrpNet.Protocol.Enumerations.V1_0_1.AccessSpecState CurrentState = GeneratedCodecRuntime.ReadEnum<global::LlrpNet.Protocol.Enumerations.V1_0_1.AccessSpecState>(reader.ReadBits(1));
        reader.ReadReservedBits(7);
        uint ROSpecID = reader.ReadUInt32();
        int offset = reader.BytePosition;
        global::LlrpNet.Protocol.Parameters.V1_0_1.AccessSpecStopTrigger? AccessSpecStopTrigger = null;
        if (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 208, false, 0U, 0U))
        {
            AccessSpecStopTrigger = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.AccessSpecStopTrigger>(registry, version, payload, ref offset);
        }
        if (AccessSpecStopTrigger is null)
        {
            throw GeneratedCodecRuntime.InvalidSequence("Required parameter 'AccessSpecStopTrigger' is missing.");
        }
        global::LlrpNet.Protocol.Parameters.V1_0_1.AccessCommand? AccessCommand = null;
        if (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 209, false, 0U, 0U))
        {
            AccessCommand = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.AccessCommand>(registry, version, payload, ref offset);
        }
        if (AccessCommand is null)
        {
            throw GeneratedCodecRuntime.InvalidSequence("Required parameter 'AccessCommand' is missing.");
        }
        global::LlrpNet.Protocol.Parameters.V1_0_1.AccessReportSpec? AccessReportSpec = null;
        if (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 239, false, 0U, 0U))
        {
            AccessReportSpec = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.AccessReportSpec>(registry, version, payload, ref offset);
        }
        var CustomItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Parameters.ILlrpParameter>();
        while (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 1023, false, 0U, 0U))
        {
            CustomItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.ILlrpParameter>(registry, version, payload, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(CustomItems.Count, 0, "CustomItems");
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Parameters.V1_0_1.AccessSpec(
            AccessSpecID,
            AntennaID,
            ProtocolID,
            CurrentState,
            ROSpecID,
            AccessSpecStopTrigger!,
            AccessCommand!,
            AccessReportSpec,
            CustomItems);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_0_1.AccessSpec parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 12;
        if (parameter.AccessSpecStopTrigger is null)
        {
            throw new global::System.ArgumentNullException("AccessSpecStopTrigger");
        }
        GeneratedCodecRuntime.ValidateParameterMatch(parameter.AccessSpecStopTrigger!, "AccessSpecStopTrigger", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.AccessSpecStopTrigger!, 208, false, 0U, 0U));
        length = checked(length + registry.GetEncodedParameterLength(version, parameter.AccessSpecStopTrigger!));
        if (parameter.AccessCommand is null)
        {
            throw new global::System.ArgumentNullException("AccessCommand");
        }
        GeneratedCodecRuntime.ValidateParameterMatch(parameter.AccessCommand!, "AccessCommand", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.AccessCommand!, 209, false, 0U, 0U));
        length = checked(length + registry.GetEncodedParameterLength(version, parameter.AccessCommand!));
        if (parameter.AccessReportSpec is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.AccessReportSpec, "AccessReportSpec", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.AccessReportSpec, 239, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.AccessReportSpec));
        }
        if (parameter.CustomItems is null)
        {
            throw new global::System.ArgumentNullException("CustomItems");
        }
        if (parameter.CustomItems.Count < 0)
        {
            throw new global::System.ArgumentException("Member 'CustomItems' requires cardinality 0..N.", "CustomItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.CustomItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "CustomItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 1023, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_0_1.AccessSpec parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        wireWriter.WriteUInt32(parameter.AccessSpecID);
        wireWriter.WriteUInt16(parameter.AntennaID);
        GeneratedCodecRuntime.ValidateEnum(parameter.ProtocolID, "ProtocolID"); wireWriter.WriteByte(checked((byte)global::System.Convert.ToUInt64(parameter.ProtocolID, global::System.Globalization.CultureInfo.InvariantCulture)));
        GeneratedCodecRuntime.ValidateEnum(parameter.CurrentState, "CurrentState"); wireWriter.WriteBits(global::System.Convert.ToUInt64(parameter.CurrentState, global::System.Globalization.CultureInfo.InvariantCulture), 1);
        wireWriter.WriteReservedBits(7);
        wireWriter.WriteUInt32(parameter.ROSpecID);
        int offset = wireWriter.BytePosition;
        offset += registry.EncodeParameter(version, parameter.AccessSpecStopTrigger!, destination[offset..]);
        offset += registry.EncodeParameter(version, parameter.AccessCommand!, destination[offset..]);
        if (parameter.AccessReportSpec is not null)
        {
            offset += registry.EncodeParameter(version, parameter.AccessReportSpec, destination[offset..]);
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in parameter.CustomItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
