// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V1_0_1;

internal sealed class AccessReportSpecCodec : global::LlrpNet.Protocol.Codecs.LlrpParameterCodec<global::LlrpNet.Protocol.Parameters.V1_0_1.AccessReportSpec>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public AccessReportSpecCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Parameters.V1_0_1.AccessReportSpec Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(payload);
        global::LlrpNet.Protocol.Enumerations.V1_0_1.AccessReportTriggerType AccessReportTrigger = GeneratedCodecRuntime.ReadEnum<global::LlrpNet.Protocol.Enumerations.V1_0_1.AccessReportTriggerType>(reader.ReadByte());
        int offset = reader.BytePosition;
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Parameters.V1_0_1.AccessReportSpec(
            AccessReportTrigger);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_0_1.AccessReportSpec parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 1;
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_0_1.AccessReportSpec parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        GeneratedCodecRuntime.ValidateEnum(parameter.AccessReportTrigger, "AccessReportTrigger"); wireWriter.WriteByte(checked((byte)global::System.Convert.ToUInt64(parameter.AccessReportTrigger, global::System.Globalization.CultureInfo.InvariantCulture)));
        int offset = wireWriter.BytePosition;
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
