// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V1_0_1;

internal sealed class LLRPStatusCodec : global::LlrpNet.Protocol.Codecs.LlrpParameterCodec<global::LlrpNet.Protocol.Parameters.V1_0_1.LLRPStatus>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public LLRPStatusCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Parameters.V1_0_1.LLRPStatus Decode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        var reader = new GeneratedWireReader(payload);
        global::LlrpNet.Protocol.Enumerations.V1_0_1.StatusCode StatusCode = GeneratedCodecRuntime.ReadEnum<global::LlrpNet.Protocol.Enumerations.V1_0_1.StatusCode>(reader.ReadUInt16());
        string ErrorDescription = reader.ReadUtf8();
        int offset = reader.BytePosition;
        global::LlrpNet.Protocol.Parameters.V1_0_1.FieldError? FieldError = null;
        if (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 288, false, 0U, 0U))
        {
            FieldError = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.FieldError>(registry, version, payload, ref offset);
        }
        global::LlrpNet.Protocol.Parameters.V1_0_1.ParameterError? ParameterError = null;
        if (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 289, false, 0U, 0U))
        {
            ParameterError = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.ParameterError>(registry, version, payload, ref offset);
        }
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Parameters.V1_0_1.LLRPStatus(
            StatusCode,
            ErrorDescription,
            FieldError,
            ParameterError);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_0_1.LLRPStatus parameter)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(parameter);
        int length = 2;
        length = checked(length + GeneratedCodecRuntime.GetUtf8Length(parameter.ErrorDescription));
        if (parameter.FieldError is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.FieldError, "FieldError", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.FieldError, 288, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.FieldError));
        }
        if (parameter.ParameterError is not null)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(parameter.ParameterError, "ParameterError", GeneratedCodecRuntime.IsParameterMatch(registry, version, parameter.ParameterError, 289, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, parameter.ParameterError));
        }
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Parameters.V1_0_1.LLRPStatus parameter,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, parameter);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        GeneratedCodecRuntime.ValidateEnum(parameter.StatusCode, "StatusCode"); wireWriter.WriteUInt16(checked((ushort)global::System.Convert.ToUInt64(parameter.StatusCode, global::System.Globalization.CultureInfo.InvariantCulture)));
        wireWriter.WriteUtf8(parameter.ErrorDescription);
        int offset = wireWriter.BytePosition;
        if (parameter.FieldError is not null)
        {
            offset += registry.EncodeParameter(version, parameter.FieldError, destination[offset..]);
        }
        if (parameter.ParameterError is not null)
        {
            offset += registry.EncodeParameter(version, parameter.ParameterError, destination[offset..]);
        }
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
