// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V1_0_1;

internal sealed class GET_READER_CAPABILITIESCodec : global::LlrpNet.Protocol.Codecs.LlrpMessageCodec<global::LlrpNet.Protocol.Messages.V1_0_1.GET_READER_CAPABILITIES>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public GET_READER_CAPABILITIESCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Messages.V1_0_1.GET_READER_CAPABILITIES Decode(
        global::LlrpNet.Core.Protocol.LlrpMessageHeader header,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(header.Version, 1);
        var version = header.Version;
        var reader = new GeneratedWireReader(payload);
        int offset = 0;
        global::LlrpNet.Protocol.Enumerations.V1_0_1.GetReaderCapabilitiesRequestedData RequestedData = GeneratedCodecRuntime.ReadEnum<global::LlrpNet.Protocol.Enumerations.V1_0_1.GetReaderCapabilitiesRequestedData>(reader.ReadByte());
        offset += reader.BytePosition;
        var CustomItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Parameters.ILlrpParameter>();
        while (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 1023, false, 0U, 0U))
        {
            CustomItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.ILlrpParameter>(registry, version, payload, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(CustomItems.Count, 0, "CustomItems");
        reader = new GeneratedWireReader(payload[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Messages.V1_0_1.GET_READER_CAPABILITIES(
            header.MessageId,
            RequestedData,
            CustomItems);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Messages.V1_0_1.GET_READER_CAPABILITIES message)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(message);
        int length = 1;
        if (message.CustomItems is null)
        {
            throw new global::System.ArgumentNullException("CustomItems");
        }
        if (message.CustomItems.Count < 0)
        {
            throw new global::System.ArgumentException("Member 'CustomItems' requires cardinality 0..N.", "CustomItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in message.CustomItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "CustomItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 1023, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Messages.V1_0_1.GET_READER_CAPABILITIES message,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, message);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        GeneratedCodecRuntime.ValidateEnum(message.RequestedData, "RequestedData"); wireWriter.WriteByte(checked((byte)global::System.Convert.ToUInt64(message.RequestedData, global::System.Globalization.CultureInfo.InvariantCulture)));
        offset += wireWriter.BytePosition;
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in message.CustomItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
