// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V1_0_1;

internal sealed class ADD_ROSPECCodec : global::LlrpNet.Protocol.Codecs.LlrpMessageCodec<global::LlrpNet.Protocol.Messages.V1_0_1.ADD_ROSPEC>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public ADD_ROSPECCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Messages.V1_0_1.ADD_ROSPEC Decode(
        global::LlrpNet.Core.Protocol.LlrpMessageHeader header,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(header.Version, 1);
        var version = header.Version;
        var reader = new GeneratedWireReader(payload);
        int offset = reader.BytePosition;
        global::LlrpNet.Protocol.Parameters.V1_0_1.ROSpec? ROSpec = null;
        if (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 177, false, 0U, 0U))
        {
            ROSpec = GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.ROSpec>(registry, version, payload, ref offset);
        }
        if (ROSpec is null)
        {
            throw GeneratedCodecRuntime.InvalidSequence("Required parameter 'ROSpec' is missing.");
        }
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Messages.V1_0_1.ADD_ROSPEC(
            header.MessageId,
            ROSpec!);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Messages.V1_0_1.ADD_ROSPEC message)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(message);
        int length = 0;
        if (message.ROSpec is null)
        {
            throw new global::System.ArgumentNullException("ROSpec");
        }
        GeneratedCodecRuntime.ValidateParameterMatch(message.ROSpec!, "ROSpec", GeneratedCodecRuntime.IsParameterMatch(registry, version, message.ROSpec!, 177, false, 0U, 0U));
        length = checked(length + registry.GetEncodedParameterLength(version, message.ROSpec!));
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Messages.V1_0_1.ADD_ROSPEC message,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, message);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = wireWriter.BytePosition;
        offset += registry.EncodeParameter(version, message.ROSpec!, destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
