// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V1_0_1;

internal sealed class RO_ACCESS_REPORTCodec : global::LlrpNet.Protocol.Codecs.LlrpMessageCodec<global::LlrpNet.Protocol.Messages.V1_0_1.RO_ACCESS_REPORT>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public RO_ACCESS_REPORTCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Messages.V1_0_1.RO_ACCESS_REPORT Decode(
        global::LlrpNet.Core.Protocol.LlrpMessageHeader header,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(header.Version, 1);
        var version = header.Version;
        var reader = new GeneratedWireReader(payload);
        int offset = 0;
        var TagReportDataItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Parameters.V1_0_1.TagReportData>();
        while (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 240, false, 0U, 0U))
        {
            TagReportDataItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.TagReportData>(registry, version, payload, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(TagReportDataItems.Count, 0, "TagReportDataItems");
        reader = new GeneratedWireReader(payload[offset..]);
        var RFSurveyReportDataItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Parameters.V1_0_1.RFSurveyReportData>();
        while (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 242, false, 0U, 0U))
        {
            RFSurveyReportDataItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.V1_0_1.RFSurveyReportData>(registry, version, payload, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(RFSurveyReportDataItems.Count, 0, "RFSurveyReportDataItems");
        reader = new GeneratedWireReader(payload[offset..]);
        var CustomItems = new global::System.Collections.Generic.List<global::LlrpNet.Protocol.Parameters.ILlrpParameter>();
        while (offset < payload.Length && GeneratedCodecRuntime.IsNextParameter(payload[offset..], 1023, false, 0U, 0U))
        {
            CustomItems.Add(GeneratedCodecRuntime.DecodeParameter<global::LlrpNet.Protocol.Parameters.ILlrpParameter>(registry, version, payload, ref offset));
        }
        GeneratedCodecRuntime.ValidateRequiredCount(CustomItems.Count, 0, "CustomItems");
        reader = new GeneratedWireReader(payload[offset..]);
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Messages.V1_0_1.RO_ACCESS_REPORT(
            header.MessageId,
            TagReportDataItems,
            RFSurveyReportDataItems,
            CustomItems);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Messages.V1_0_1.RO_ACCESS_REPORT message)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(message);
        int length = 0;
        if (message.TagReportDataItems is null)
        {
            throw new global::System.ArgumentNullException("TagReportDataItems");
        }
        if (message.TagReportDataItems.Count < 0)
        {
            throw new global::System.ArgumentException("Member 'TagReportDataItems' requires cardinality 0..N.", "TagReportDataItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in message.TagReportDataItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "TagReportDataItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 240, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        if (message.RFSurveyReportDataItems is null)
        {
            throw new global::System.ArgumentNullException("RFSurveyReportDataItems");
        }
        if (message.RFSurveyReportDataItems.Count < 0)
        {
            throw new global::System.ArgumentException("Member 'RFSurveyReportDataItems' requires cardinality 0..N.", "RFSurveyReportDataItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in message.RFSurveyReportDataItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "RFSurveyReportDataItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 242, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        if (message.CustomItems is null)
        {
            throw new global::System.ArgumentNullException("CustomItems");
        }
        if (message.CustomItems.Count < 0)
        {
            throw new global::System.ArgumentException("Member 'CustomItems' requires cardinality 0..N.", "CustomItems");
        }
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in message.CustomItems)
        {
            GeneratedCodecRuntime.ValidateParameterMatch(nested, "CustomItems", GeneratedCodecRuntime.IsParameterMatch(registry, version, nested, 1023, false, 0U, 0U));
            length = checked(length + registry.GetEncodedParameterLength(version, nested));
        }
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Messages.V1_0_1.RO_ACCESS_REPORT message,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, message);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in message.TagReportDataItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in message.RFSurveyReportDataItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        foreach (global::LlrpNet.Protocol.Parameters.ILlrpParameter nested in message.CustomItems)
        {
            offset += registry.EncodeParameter(version, nested, destination[offset..]);
        }
        wireWriter = new GeneratedWireWriter(destination[offset..]);
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
