// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Codecs.V1_0_1;

internal sealed class KEEPALIVE_ACKCodec : global::LlrpNet.Protocol.Codecs.LlrpMessageCodec<global::LlrpNet.Protocol.Messages.V1_0_1.KEEPALIVE_ACK>
{
    private readonly global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry;

    public KEEPALIVE_ACKCodec(global::LlrpNet.Protocol.Registry.LlrpCodecRegistry registry)
    {
        global::System.ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public override global::LlrpNet.Protocol.Messages.V1_0_1.KEEPALIVE_ACK Decode(
        global::LlrpNet.Core.Protocol.LlrpMessageHeader header,
        global::System.ReadOnlySpan<byte> payload)
    {
        GeneratedCodecRuntime.ValidateVersion(header.Version, 1);
        var version = header.Version;
        var reader = new GeneratedWireReader(payload);
        int offset = 0;
        GeneratedCodecRuntime.ValidateDecodedEnd(offset, payload.Length);
        return new global::LlrpNet.Protocol.Messages.V1_0_1.KEEPALIVE_ACK(
            header.MessageId);
    }

    public override int GetEncodedPayloadLength(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Messages.V1_0_1.KEEPALIVE_ACK message)
    {
        GeneratedCodecRuntime.ValidateVersion(version, 1);
        global::System.ArgumentNullException.ThrowIfNull(message);
        int length = 0;
        return length;
    }

    public override int Encode(
        global::LlrpNet.Core.Protocol.LlrpProtocolVersion version,
        global::LlrpNet.Protocol.Messages.V1_0_1.KEEPALIVE_ACK message,
        global::System.Span<byte> destination)
    {
        int expectedLength = GetEncodedPayloadLength(version, message);
        GeneratedCodecRuntime.ValidateDestination(destination, expectedLength);
        destination.Clear();
        var wireWriter = new GeneratedWireWriter(destination);
        int offset = 0;
        if (offset != destination.Length)
        {
            throw new global::System.InvalidOperationException("Generated codec wrote an unexpected payload length.");
        }
        return offset;
    }

}
