<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LlrpSdk\LlrpSdk.csproj" />
    <ProjectReference Include="..\LlrpSdk.Extensions.Impinj\LlrpSdk.Extensions.Impinj.csproj" />
  </ItemGroup>
</Project>
