// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Enumerations.V1_0_1;

/// <summary>Generated LLRP enumeration 'GetReaderCapabilitiesRequestedData'.</summary>
public enum GetReaderCapabilitiesRequestedData : long
{
    All = 0L,
    General_Device_Capabilities = 1L,
    LLRP_Capabilities = 2L,
    Regulatory_Capabilities = 3L,
    LLRP_Air_Protocol_Capabilities = 4L,
}
