// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Enumerations.V1_0_1;

/// <summary>Generated LLRP enumeration 'ROSpecEventType'.</summary>
public enum ROSpecEventType : long
{
    Start_Of_ROSpec = 0L,
    End_Of_ROSpec = 1L,
    Preemption_Of_ROSpec = 2L,
}
