// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Enumerations.V1_0_1;

/// <summary>Generated LLRP enumeration 'ConnectionAttemptStatusType'.</summary>
public enum ConnectionAttemptStatusType : long
{
    Success = 0L,
    Failed_A_Reader_Initiated_Connection_Already_Exists = 1L,
    Failed_A_Client_Initiated_Connection_Already_Exists = 2L,
    Failed_Reason_Other_Than_A_Connection_Already_Exists = 3L,
    Another_Connection_Attempted = 4L,
}
