// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Enumerations.V1_0_1;

/// <summary>Generated LLRP enumeration 'C1G2LockDataField'.</summary>
public enum C1G2LockDataField : long
{
    Kill_Password = 0L,
    Access_Password = 1L,
    EPC_Memory = 2L,
    TID_Memory = 3L,
    User_Memory = 4L,
}
