// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Enumerations.V1_0_1;

/// <summary>Generated LLRP enumeration 'C1G2LockResultType'.</summary>
public enum C1G2LockResultType : long
{
    Success = 0L,
    Insufficient_Power = 1L,
    Nonspecific_Tag_Error = 2L,
    No_Response_From_Tag = 3L,
    Nonspecific_Reader_Error = 4L,
}
