// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Messages.V1_0_1;

/// <summary>Generated LLRP message 'CUSTOM_MESSAGE'.</summary>
/// <param name="MessageId">The common LLRP message identifier.</param>
/// <param name="VendorIdentifier">Wire field 'VendorIdentifier' (U32).</param>
/// <param name="MessageSubtype">Wire field 'MessageSubtype' (U8).</param>
/// <param name="Data">Wire field 'Data' (BytesToEnd).</param>
public sealed record CUSTOM_MESSAGE(
    uint MessageId,
    uint VendorIdentifier,
    byte MessageSubtype,
    global::System.ReadOnlyMemory<byte> Data
) : global::LlrpNet.Protocol.Messages.ILlrpMessage
{
    public const ushort TypeNumber = 1023;
    public const ushort MessageType = TypeNumber;
}
