// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Messages.V1_0_1;

/// <summary>Generated LLRP message 'GET_READER_CAPABILITIES_RESPONSE'.</summary>
/// <param name="MessageId">The common LLRP message identifier.</param>
/// <param name="LLRPStatus">LLRP parameter 'LLRPStatus' with cardinality 1..1.</param>
/// <param name="GeneralDeviceCapabilities">LLRP parameter 'GeneralDeviceCapabilities' with cardinality 0..1.</param>
/// <param name="LLRPCapabilities">LLRP parameter 'LLRPCapabilities' with cardinality 0..1.</param>
/// <param name="RegulatoryCapabilities">LLRP parameter 'RegulatoryCapabilities' with cardinality 0..1.</param>
/// <param name="AirProtocolLLRPCapabilities">LLRP choice 'AirProtocolLLRPCapabilities' with cardinality 0..1.</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record GET_READER_CAPABILITIES_RESPONSE(
    uint MessageId,
    global::LlrpNet.Protocol.Parameters.V1_0_1.LLRPStatus LLRPStatus,
    global::LlrpNet.Protocol.Parameters.V1_0_1.GeneralDeviceCapabilities? GeneralDeviceCapabilities,
    global::LlrpNet.Protocol.Parameters.V1_0_1.LLRPCapabilities? LLRPCapabilities,
    global::LlrpNet.Protocol.Parameters.V1_0_1.RegulatoryCapabilities? RegulatoryCapabilities,
    global::LlrpNet.Protocol.Choices.V1_0_1.IAirProtocolLLRPCapabilities? AirProtocolLLRPCapabilities,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Messages.ILlrpMessage
{
    public const ushort TypeNumber = 11;
    public const ushort MessageType = TypeNumber;
}
