// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Messages.V1_0_1;

/// <summary>Generated LLRP message 'STOP_ROSPEC_RESPONSE'.</summary>
/// <param name="MessageId">The common LLRP message identifier.</param>
/// <param name="LLRPStatus">LLRP parameter 'LLRPStatus' with cardinality 1..1.</param>
public sealed record STOP_ROSPEC_RESPONSE(
    uint MessageId,
    global::LlrpNet.Protocol.Parameters.V1_0_1.LLRPStatus LLRPStatus
) : global::LlrpNet.Protocol.Messages.ILlrpMessage
{
    public const ushort TypeNumber = 33;
    public const ushort MessageType = TypeNumber;
}
