// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Messages.V1_0_1;

/// <summary>Generated LLRP message 'GET_ROSPECS'.</summary>
/// <param name="MessageId">The common LLRP message identifier.</param>
public sealed record GET_ROSPECS(
    uint MessageId
) : global::LlrpNet.Protocol.Messages.ILlrpMessage
{
    public const ushort TypeNumber = 26;
    public const ushort MessageType = TypeNumber;
}
