// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Messages.V1_0_1;

/// <summary>Generated LLRP message 'ADD_ACCESSSPEC'.</summary>
/// <param name="MessageId">The common LLRP message identifier.</param>
/// <param name="AccessSpec">LLRP parameter 'AccessSpec' with cardinality 1..1.</param>
public sealed record ADD_ACCESSSPEC(
    uint MessageId,
    global::LlrpNet.Protocol.Parameters.V1_0_1.AccessSpec AccessSpec
) : global::LlrpNet.Protocol.Messages.ILlrpMessage
{
    public const ushort TypeNumber = 40;
    public const ushort MessageType = TypeNumber;
}
