// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Messages.V1_0_1;

/// <summary>Generated LLRP message 'ENABLE_EVENTS_AND_REPORTS'.</summary>
/// <param name="MessageId">The common LLRP message identifier.</param>
public sealed record ENABLE_EVENTS_AND_REPORTS(
    uint MessageId
) : global::LlrpNet.Protocol.Messages.ILlrpMessage
{
    public const ushort TypeNumber = 64;
    public const ushort MessageType = TypeNumber;
}
