<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="artifacts\**" />
    <EmbeddedResource Remove="artifacts\**" />
    <None Remove="artifacts\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LlrpNet.Core\LlrpNet.Core.csproj" />
  </ItemGroup>
</Project>

