<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Spectre.Console.Cli" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LlrpNet\LlrpNet.Core\LlrpNet.Core.csproj" />
    <ProjectReference Include="..\LlrpNet\LlrpNet.Protocol\LlrpNet.Protocol.csproj" />
    <ProjectReference Include="..\LlrpSdk.Extensions.Abstractions\LlrpSdk.Extensions.Abstractions.csproj" />
    <ProjectReference Include="..\LlrpSdk\LlrpSdk.csproj" />
    <ProjectReference Include="..\LlrpSdk.Extensions.Abstractions\LlrpSdk.Extensions.Abstractions.csproj" />
    <ProjectReference Include="..\LlrpSdk.Extensions.Impinj\LlrpSdk.Extensions.Impinj.csproj" />
    <ProjectReference Include="..\LlrpSdk.Extensions.Seuic\LlrpSdk.Extensions.Seuic.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>LlrpCli.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
