// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Zebra.Choices.V1_0_1;

/// <summary>Marks a parameter accepted by the LLRP choice 'MotoFilterTimeFormatChoice'.</summary>
public interface IMotoFilterTimeFormatChoice : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
}
