// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V2_0;

/// <summary>Generated LLRP TLV parameter 'UTCTimestamp'.</summary>
/// <param name="Microseconds">Wire field 'Microseconds' (U64).</param>
public sealed record UTCTimestamp(
    ulong Microseconds
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V2_0.ITimestamp
{
    public const ushort TypeNumber = 128;
    public const ushort ParameterType = 128;
}
