// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V2_0;

/// <summary>Generated LLRP TLV parameter 'ROBoundarySpec'.</summary>
/// <param name="ROSpecStartTrigger">LLRP parameter 'ROSpecStartTrigger' with cardinality 1..1.</param>
/// <param name="ROSpecStopTrigger">LLRP parameter 'ROSpecStopTrigger' with cardinality 1..1.</param>
public sealed record ROBoundarySpec(
    global::LlrpNet.Protocol.Parameters.V2_0.ROSpecStartTrigger ROSpecStartTrigger,
    global::LlrpNet.Protocol.Parameters.V2_0.ROSpecStopTrigger ROSpecStopTrigger
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 178;
    public const ushort ParameterType = 178;
}
