// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V2_0;

/// <summary>Generated LLRP TLV parameter 'ClientRequestOpSpec'.</summary>
/// <param name="OpSpecID">Wire field 'OpSpecID' (U16).</param>
public sealed record ClientRequestOpSpec(
    ushort OpSpecID
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V2_0.IAccessCommandOpSpec
{
    public const ushort TypeNumber = 210;
    public const ushort ParameterType = 210;
}
