// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V2_0;

/// <summary>Generated LLRP TLV parameter 'GPIPortCurrentState'.</summary>
/// <param name="GPIPortNum">Wire field 'GPIPortNum' (U16).</param>
/// <param name="Config">Wire field 'Config' (U1).</param>
/// <param name="State">Wire field 'State' (U8).</param>
public sealed record GPIPortCurrentState(
    ushort GPIPortNum,
    bool Config,
    global::LlrpNet.Protocol.Enumerations.V2_0.GPIPortState State
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 225;
    public const ushort ParameterType = 225;
}
