// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V2_0;

/// <summary>Generated LLRP TV parameter 'ClientRequestOpSpecResult'.</summary>
/// <param name="OpSpecID">Wire field 'OpSpecID' (U16).</param>
public sealed record ClientRequestOpSpecResult(
    ushort OpSpecID
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V2_0.IAccessCommandOpSpecResult
{
    public const ushort TypeNumber = 15;
    public const ushort ParameterType = 15;
}
