// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V2_0;

/// <summary>Generated LLRP TV parameter 'C1G2_PC'.</summary>
/// <param name="PC_Bits">Wire field 'PC_Bits' (U16).</param>
public sealed record C1G2_PC(
    ushort PC_Bits
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V2_0.IAirProtocolTagData
{
    public const ushort TypeNumber = 12;
    public const ushort ParameterType = 12;
}
