// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V2_0;

/// <summary>Generated LLRP TLV parameter 'C1G2KillOpSpecResult'.</summary>
/// <param name="Result">Wire field 'Result' (U8).</param>
/// <param name="OpSpecID">Wire field 'OpSpecID' (U16).</param>
public sealed record C1G2KillOpSpecResult(
    global::LlrpNet.Protocol.Enumerations.V2_0.C1G2KillResultType Result,
    ushort OpSpecID
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V2_0.IAccessCommandOpSpecResult
{
    public const ushort TypeNumber = 351;
    public const ushort ParameterType = 351;
}
