// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V2_0;

/// <summary>Generated LLRP TLV parameter 'C1G2BlockWriteOpSpecResult'.</summary>
/// <param name="Result">Wire field 'Result' (U8).</param>
/// <param name="OpSpecID">Wire field 'OpSpecID' (U16).</param>
/// <param name="NumWordsWritten">Wire field 'NumWordsWritten' (U16).</param>
public sealed record C1G2BlockWriteOpSpecResult(
    global::LlrpNet.Protocol.Enumerations.V2_0.C1G2BlockWriteResultType Result,
    ushort OpSpecID,
    ushort NumWordsWritten
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V2_0.IAccessCommandOpSpecResult
{
    public const ushort TypeNumber = 354;
    public const ushort ParameterType = 354;
}
