// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V2_0;

/// <summary>Generated LLRP TLV parameter 'C1G2AuthComm'.</summary>
/// <param name="OpSpecID">Wire field 'OpSpecID' (U16).</param>
/// <param name="AccessPassword">Wire field 'AccessPassword' (U32).</param>
/// <param name="L">Wire field 'L' (U1).</param>
/// <param name="MsgLen">Wire field 'MsgLen' (U16).</param>
/// <param name="Message">Wire field 'Message' (U1Vector).</param>
public sealed record C1G2AuthComm(
    ushort OpSpecID,
    uint AccessPassword,
    bool L,
    ushort MsgLen,
    global::System.Collections.Generic.IReadOnlyList<bool> Message
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V2_0.IAccessCommandOpSpec, global::LlrpNet.Protocol.Choices.V2_0.IC1G2OpSpec, global::LlrpNet.Protocol.Choices.V2_0.IAirProtocolOpSpec
{
    public const ushort TypeNumber = 368;
    public const ushort ParameterType = 368;
}
