// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V2_0;

/// <summary>Generated LLRP TLV parameter 'C1G2ReadBuffer'.</summary>
/// <param name="OpSpecID">Wire field 'OpSpecID' (U16).</param>
/// <param name="AccessPassword">Wire field 'AccessPassword' (U32).</param>
/// <param name="WordPtr">Wire field 'WordPtr' (U16).</param>
/// <param name="NumBits">Wire field 'NumBits' (U16).</param>
public sealed record C1G2ReadBuffer(
    ushort OpSpecID,
    uint AccessPassword,
    ushort WordPtr,
    ushort NumBits
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V2_0.IAccessCommandOpSpec, global::LlrpNet.Protocol.Choices.V2_0.IC1G2OpSpec, global::LlrpNet.Protocol.Choices.V2_0.IAirProtocolOpSpec
{
    public const ushort TypeNumber = 370;
    public const ushort ParameterType = 370;
}
