// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V2_0;

/// <summary>Generated LLRP TLV parameter 'C1G2TagPrivilege'.</summary>
/// <param name="OpSpecID">Wire field 'OpSpecID' (U16).</param>
/// <param name="AccessPassword">Wire field 'AccessPassword' (U32).</param>
/// <param name="S">Wire field 'S' (U1).</param>
/// <param name="L">Wire field 'L' (U1).</param>
/// <param name="A">Wire field 'A' (U1).</param>
/// <param name="T">Wire field 'T' (U1).</param>
/// <param name="KeyID">Wire field 'KeyID' (U16).</param>
/// <param name="Privilege">Wire field 'Privilege' (U16).</param>
public sealed record C1G2TagPrivilege(
    ushort OpSpecID,
    uint AccessPassword,
    bool S,
    bool L,
    bool A,
    bool T,
    ushort KeyID,
    ushort Privilege
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V2_0.IAccessCommandOpSpec, global::LlrpNet.Protocol.Choices.V2_0.IC1G2OpSpec, global::LlrpNet.Protocol.Choices.V2_0.IAirProtocolOpSpec
{
    public const ushort TypeNumber = 373;
    public const ushort ParameterType = 373;
}
