// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V2_0;

/// <summary>Generated LLRP TLV parameter 'C1G2Untraceable'.</summary>
/// <param name="OpSpecID">Wire field 'OpSpecID' (U16).</param>
/// <param name="AccessPassword">Wire field 'AccessPassword' (U32).</param>
/// <param name="U">Wire field 'U' (U1).</param>
/// <param name="EPCBit5">Wire field 'EPCBit5' (U1).</param>
/// <param name="EPCBit4">Wire field 'EPCBit4' (U1).</param>
/// <param name="EPCBit3">Wire field 'EPCBit3' (U1).</param>
/// <param name="EPCBit2">Wire field 'EPCBit2' (U1).</param>
/// <param name="EPCBit1">Wire field 'EPCBit1' (U1).</param>
/// <param name="EPCBit0">Wire field 'EPCBit0' (U1).</param>
/// <param name="TID">Wire field 'TID' (U2).</param>
/// <param name="User">Wire field 'User' (U1).</param>
/// <param name="Range">Wire field 'Range' (U2).</param>
public sealed record C1G2Untraceable(
    ushort OpSpecID,
    uint AccessPassword,
    bool U,
    bool EPCBit5,
    bool EPCBit4,
    bool EPCBit3,
    bool EPCBit2,
    bool EPCBit1,
    bool EPCBit0,
    byte TID,
    bool User,
    byte Range
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V2_0.IAccessCommandOpSpec, global::LlrpNet.Protocol.Choices.V2_0.IC1G2OpSpec, global::LlrpNet.Protocol.Choices.V2_0.IAirProtocolOpSpec
{
    public const ushort TypeNumber = 380;
    public const ushort ParameterType = 380;
}
