// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Impinj.Enumerations.V1_0_1;

/// <summary>Generated LLRP custom enumeration 'ImpinjDirectionDiagnosticReportLevel'.</summary>
public enum ImpinjDirectionDiagnosticReportLevel : long
{
    Off = 0L,
    Basic = 1L,
    Extended = 2L,
    Debug = 3L,
}
