// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Impinj.Enumerations.V1_0_1;

/// <summary>Generated LLRP custom enumeration 'ImpinjDirectionReportType'.</summary>
public enum ImpinjDirectionReportType : long
{
    Entry = 0L,
    Update = 1L,
    Exit = 2L,
}
