// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Impinj.Enumerations.V1_0_1;

/// <summary>Generated LLRP custom enumeration 'ImpinjGen2XProtection'.</summary>
public enum ImpinjGen2XProtection : long
{
    None = 0L,
    Parity = 1L,
    CRC5 = 2L,
    CRC5_Plus = 3L,
}
