// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_1;

/// <summary>Generated LLRP TLV parameter 'Uptime'.</summary>
/// <param name="Microseconds">Wire field 'Microseconds' (U64).</param>
public sealed record Uptime(
    ulong Microseconds
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V1_1.ITimestamp
{
    public const ushort TypeNumber = 129;
    public const ushort ParameterType = 129;
}
