// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_1;

/// <summary>Generated LLRP TLV parameter 'GPIOCapabilities'.</summary>
/// <param name="NumGPIs">Wire field 'NumGPIs' (U16).</param>
/// <param name="NumGPOs">Wire field 'NumGPOs' (U16).</param>
public sealed record GPIOCapabilities(
    ushort NumGPIs,
    ushort NumGPOs
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 141;
    public const ushort ParameterType = 141;
}
