// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_1;

/// <summary>Generated LLRP TLV parameter 'UHFBandCapabilities'.</summary>
/// <param name="TransmitPowerLevelTableEntryItems">LLRP parameter 'TransmitPowerLevelTableEntry' with cardinality 1..N.</param>
/// <param name="FrequencyInformation">LLRP parameter 'FrequencyInformation' with cardinality 1..1.</param>
/// <param name="AirProtocolUHFRFModeTableItems">LLRP choice 'AirProtocolUHFRFModeTable' with cardinality 1..N.</param>
/// <param name="RFSurveyFrequencyCapabilities">LLRP parameter 'RFSurveyFrequencyCapabilities' with cardinality 0..1.</param>
public sealed record UHFBandCapabilities(
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.V1_1.TransmitPowerLevelTableEntry> TransmitPowerLevelTableEntryItems,
    global::LlrpNet.Protocol.Parameters.V1_1.FrequencyInformation FrequencyInformation,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Choices.V1_1.IAirProtocolUHFRFModeTable> AirProtocolUHFRFModeTableItems,
    global::LlrpNet.Protocol.Parameters.V1_1.RFSurveyFrequencyCapabilities? RFSurveyFrequencyCapabilities
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 144;
    public const ushort ParameterType = 144;
}
