// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_1;

/// <summary>Generated LLRP TLV parameter 'ROSpecStartTrigger'.</summary>
/// <param name="ROSpecStartTriggerType">Wire field 'ROSpecStartTriggerType' (U8).</param>
/// <param name="PeriodicTriggerValue">LLRP parameter 'PeriodicTriggerValue' with cardinality 0..1.</param>
/// <param name="GPITriggerValue">LLRP parameter 'GPITriggerValue' with cardinality 0..1.</param>
public sealed record ROSpecStartTrigger(
    global::LlrpNet.Protocol.Enumerations.V1_1.ROSpecStartTriggerType ROSpecStartTriggerType,
    global::LlrpNet.Protocol.Parameters.V1_1.PeriodicTriggerValue? PeriodicTriggerValue,
    global::LlrpNet.Protocol.Parameters.V1_1.GPITriggerValue? GPITriggerValue
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 179;
    public const ushort ParameterType = 179;
}
