// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_1;

/// <summary>Generated LLRP TLV parameter 'AISpec'.</summary>
/// <param name="AntennaIDs">Wire field 'AntennaIDs' (U16Vector).</param>
/// <param name="AISpecStopTrigger">LLRP parameter 'AISpecStopTrigger' with cardinality 1..1.</param>
/// <param name="InventoryParameterSpecItems">LLRP parameter 'InventoryParameterSpec' with cardinality 1..N.</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record AISpec(
    global::System.Collections.Generic.IReadOnlyList<ushort> AntennaIDs,
    global::LlrpNet.Protocol.Parameters.V1_1.AISpecStopTrigger AISpecStopTrigger,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.V1_1.InventoryParameterSpec> InventoryParameterSpecItems,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V1_1.ISpecParameter
{
    public const ushort TypeNumber = 183;
    public const ushort ParameterType = 183;
}
