// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_1;

/// <summary>Generated LLRP TLV parameter 'InventoryParameterSpec'.</summary>
/// <param name="InventoryParameterSpecID">Wire field 'InventoryParameterSpecID' (U16).</param>
/// <param name="ProtocolID">Wire field 'ProtocolID' (U8).</param>
/// <param name="AntennaConfigurationItems">LLRP parameter 'AntennaConfiguration' with cardinality 0..N.</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record InventoryParameterSpec(
    ushort InventoryParameterSpecID,
    global::LlrpNet.Protocol.Enumerations.V1_1.AirProtocols ProtocolID,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.V1_1.AntennaConfiguration> AntennaConfigurationItems,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 186;
    public const ushort ParameterType = 186;
}
