// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_1;

/// <summary>Generated LLRP TLV parameter 'RFTransmitter'.</summary>
/// <param name="HopTableID">Wire field 'HopTableID' (U16).</param>
/// <param name="ChannelIndex">Wire field 'ChannelIndex' (U16).</param>
/// <param name="TransmitPower">Wire field 'TransmitPower' (U16).</param>
public sealed record RFTransmitter(
    ushort HopTableID,
    ushort ChannelIndex,
    ushort TransmitPower
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 224;
    public const ushort ParameterType = 224;
}
