// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_1;

/// <summary>Generated LLRP TLV parameter 'ROReportSpec'.</summary>
/// <param name="ROReportTrigger">Wire field 'ROReportTrigger' (U8).</param>
/// <param name="N">Wire field 'N' (U16).</param>
/// <param name="TagReportContentSelector">LLRP parameter 'TagReportContentSelector' with cardinality 1..1.</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ROReportSpec(
    global::LlrpNet.Protocol.Enumerations.V1_1.ROReportTriggerType ROReportTrigger,
    ushort N,
    global::LlrpNet.Protocol.Parameters.V1_1.TagReportContentSelector TagReportContentSelector,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 237;
    public const ushort ParameterType = 237;
}
