// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_1;

/// <summary>Generated LLRP TLV parameter 'TagReportContentSelector'.</summary>
/// <param name="EnableROSpecID">Wire field 'EnableROSpecID' (U1).</param>
/// <param name="EnableSpecIndex">Wire field 'EnableSpecIndex' (U1).</param>
/// <param name="EnableInventoryParameterSpecID">Wire field 'EnableInventoryParameterSpecID' (U1).</param>
/// <param name="EnableAntennaID">Wire field 'EnableAntennaID' (U1).</param>
/// <param name="EnableChannelIndex">Wire field 'EnableChannelIndex' (U1).</param>
/// <param name="EnablePeakRSSI">Wire field 'EnablePeakRSSI' (U1).</param>
/// <param name="EnableFirstSeenTimestamp">Wire field 'EnableFirstSeenTimestamp' (U1).</param>
/// <param name="EnableLastSeenTimestamp">Wire field 'EnableLastSeenTimestamp' (U1).</param>
/// <param name="EnableTagSeenCount">Wire field 'EnableTagSeenCount' (U1).</param>
/// <param name="EnableAccessSpecID">Wire field 'EnableAccessSpecID' (U1).</param>
/// <param name="AirProtocolEPCMemorySelectorItems">LLRP choice 'AirProtocolEPCMemorySelector' with cardinality 0..N.</param>
public sealed record TagReportContentSelector(
    bool EnableROSpecID,
    bool EnableSpecIndex,
    bool EnableInventoryParameterSpecID,
    bool EnableAntennaID,
    bool EnableChannelIndex,
    bool EnablePeakRSSI,
    bool EnableFirstSeenTimestamp,
    bool EnableLastSeenTimestamp,
    bool EnableTagSeenCount,
    bool EnableAccessSpecID,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Choices.V1_1.IAirProtocolEPCMemorySelector> AirProtocolEPCMemorySelectorItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 238;
    public const ushort ParameterType = 238;
}
