// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_1;

/// <summary>Generated LLRP TV parameter 'FirstSeenTimestampUTC'.</summary>
/// <param name="Microseconds">Wire field 'Microseconds' (U64).</param>
public sealed record FirstSeenTimestampUTC(
    ulong Microseconds
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 2;
    public const ushort ParameterType = 2;
}
