// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_1;

/// <summary>Generated LLRP TV parameter 'FirstSeenTimestampUptime'.</summary>
/// <param name="Microseconds">Wire field 'Microseconds' (U64).</param>
public sealed record FirstSeenTimestampUptime(
    ulong Microseconds
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 3;
    public const ushort ParameterType = 3;
}
