// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_1;

/// <summary>Generated LLRP TLV parameter 'ReaderEventNotificationSpec'.</summary>
/// <param name="EventNotificationStateItems">LLRP parameter 'EventNotificationState' with cardinality 1..N.</param>
public sealed record ReaderEventNotificationSpec(
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.V1_1.EventNotificationState> EventNotificationStateItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 244;
    public const ushort ParameterType = 244;
}
