// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_1;

/// <summary>Generated LLRP TLV parameter 'HoppingEvent'.</summary>
/// <param name="HopTableID">Wire field 'HopTableID' (U16).</param>
/// <param name="NextChannelIndex">Wire field 'NextChannelIndex' (U16).</param>
public sealed record HoppingEvent(
    ushort HopTableID,
    ushort NextChannelIndex
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 247;
    public const ushort ParameterType = 247;
}
