// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_1;

/// <summary>Generated LLRP TLV parameter 'ReaderExceptionEvent'.</summary>
/// <param name="Message">Wire field 'Message' (Utf8Vector).</param>
/// <param name="ROSpecID">LLRP parameter 'ROSpecID' with cardinality 0..1.</param>
/// <param name="SpecIndex">LLRP parameter 'SpecIndex' with cardinality 0..1.</param>
/// <param name="InventoryParameterSpecID">LLRP parameter 'InventoryParameterSpecID' with cardinality 0..1.</param>
/// <param name="AntennaID">LLRP parameter 'AntennaID' with cardinality 0..1.</param>
/// <param name="AccessSpecID">LLRP parameter 'AccessSpecID' with cardinality 0..1.</param>
/// <param name="OpSpecID">LLRP parameter 'OpSpecID' with cardinality 0..1.</param>
/// <param name="CustomItems">LLRP parameter 'Custom' with cardinality 0..N.</param>
public sealed record ReaderExceptionEvent(
    string Message,
    global::LlrpNet.Protocol.Parameters.V1_1.ROSpecID? ROSpecID,
    global::LlrpNet.Protocol.Parameters.V1_1.SpecIndex? SpecIndex,
    global::LlrpNet.Protocol.Parameters.V1_1.InventoryParameterSpecID? InventoryParameterSpecID,
    global::LlrpNet.Protocol.Parameters.V1_1.AntennaID? AntennaID,
    global::LlrpNet.Protocol.Parameters.V1_1.AccessSpecID? AccessSpecID,
    global::LlrpNet.Protocol.Parameters.V1_1.OpSpecID? OpSpecID,
    global::System.Collections.Generic.IReadOnlyList<global::LlrpNet.Protocol.Parameters.ILlrpParameter> CustomItems
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 252;
    public const ushort ParameterType = 252;
}
