// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_1;

/// <summary>Generated LLRP TLV parameter 'C1G2LLRPCapabilities'.</summary>
/// <param name="CanSupportBlockErase">Wire field 'CanSupportBlockErase' (U1).</param>
/// <param name="CanSupportBlockWrite">Wire field 'CanSupportBlockWrite' (U1).</param>
/// <param name="CanSupportBlockPermalock">Wire field 'CanSupportBlockPermalock' (U1).</param>
/// <param name="CanSupportTagRecommissioning">Wire field 'CanSupportTagRecommissioning' (U1).</param>
/// <param name="CanSupportUMIMethod2">Wire field 'CanSupportUMIMethod2' (U1).</param>
/// <param name="CanSupportXPC">Wire field 'CanSupportXPC' (U1).</param>
/// <param name="MaxNumSelectFiltersPerQuery">Wire field 'MaxNumSelectFiltersPerQuery' (U16).</param>
public sealed record C1G2LLRPCapabilities(
    bool CanSupportBlockErase,
    bool CanSupportBlockWrite,
    bool CanSupportBlockPermalock,
    bool CanSupportTagRecommissioning,
    bool CanSupportUMIMethod2,
    bool CanSupportXPC,
    ushort MaxNumSelectFiltersPerQuery
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V1_1.IAirProtocolLLRPCapabilities
{
    public const ushort TypeNumber = 327;
    public const ushort ParameterType = 327;
}
