// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_1;

/// <summary>Generated LLRP TLV parameter 'C1G2EPCMemorySelector'.</summary>
/// <param name="EnableCRC">Wire field 'EnableCRC' (U1).</param>
/// <param name="EnablePCBits">Wire field 'EnablePCBits' (U1).</param>
public sealed record C1G2EPCMemorySelector(
    bool EnableCRC,
    bool EnablePCBits
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V1_1.IAirProtocolEPCMemorySelector
{
    public const ushort TypeNumber = 348;
    public const ushort ParameterType = 348;
}
