// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_1;

/// <summary>Generated LLRP TLV parameter 'C1G2LockOpSpecResult'.</summary>
/// <param name="Result">Wire field 'Result' (U8).</param>
/// <param name="OpSpecID">Wire field 'OpSpecID' (U16).</param>
public sealed record C1G2LockOpSpecResult(
    global::LlrpNet.Protocol.Enumerations.V1_1.C1G2LockResultType Result,
    ushort OpSpecID
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V1_1.IAccessCommandOpSpecResult
{
    public const ushort TypeNumber = 352;
    public const ushort ParameterType = 352;
}
