// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_1;

/// <summary>Generated LLRP TLV parameter 'SpecLoopEvent'.</summary>
/// <param name="ROSpecID">Wire field 'ROSpecID' (U32).</param>
/// <param name="LoopCount">Wire field 'LoopCount' (U32).</param>
public sealed record SpecLoopEvent(
    uint ROSpecID,
    uint LoopCount
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
    public const ushort TypeNumber = 356;
    public const ushort ParameterType = 356;
}
