// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Parameters.V1_1;

/// <summary>Generated LLRP TLV parameter 'C1G2GetBlockPermalockStatusOpSpecResult'.</summary>
/// <param name="Result">Wire field 'Result' (U8).</param>
/// <param name="OpSpecID">Wire field 'OpSpecID' (U16).</param>
/// <param name="PermalockStatus">Wire field 'PermalockStatus' (U16Vector).</param>
public sealed record C1G2GetBlockPermalockStatusOpSpecResult(
    global::LlrpNet.Protocol.Enumerations.V1_1.C1G2GetBlockPermalockStatusResultType Result,
    ushort OpSpecID,
    global::System.Collections.Generic.IReadOnlyList<ushort> PermalockStatus
) : global::LlrpNet.Protocol.Parameters.ILlrpParameter, global::LlrpNet.Protocol.Choices.V1_1.IAccessCommandOpSpecResult
{
    public const ushort TypeNumber = 362;
    public const ushort ParameterType = 362;
}
