// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Choices.V2_0;

/// <summary>Marks a parameter accepted by the LLRP choice 'EPCParameter'.</summary>
public interface IEPCParameter : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
}
