// <auto-generated />
#nullable enable

namespace LlrpNet.Protocol.Choices.V2_0;

/// <summary>Marks a parameter accepted by the LLRP choice 'AirProtocolEPCMemorySelector'.</summary>
public interface IAirProtocolEPCMemorySelector : global::LlrpNet.Protocol.Parameters.ILlrpParameter
{
}
