<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LlrpNet\LlrpNet.Protocol.Impinj\LlrpNet.Protocol.Impinj.csproj" />
    <ProjectReference Include="..\..\src\LlrpSdk\LlrpSdk.csproj" />
    <ProjectReference Include="..\..\src\LlrpSdk.Extensions.Abstractions\LlrpSdk.Extensions.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\LlrpSdk.Extensions.Impinj\LlrpSdk.Extensions.Impinj.csproj" />
    <ProjectReference Include="..\..\src\LlrpSdk.Extensions.Zebra\LlrpSdk.Extensions.Zebra.csproj" />
  </ItemGroup>
</Project>
